-- =====================================================================
-- SINAN ERP · 01 - TABLAS
-- Crea todas las tablas del sistema y sus relaciones.
-- Se puede correr más de una vez: si la tabla ya existe, no la toca.
-- =====================================================================

-- ---------- Configuración (una sola fila con los datos de la marca) ----------
create table if not exists configuracion (
  id                   int primary key default 1 check (id = 1),
  nombre_marca         text not null default 'Sinan',
  frase                text default 'Movete a tu ritmo',
  descripcion          text,
  instagram            text,
  tiktok               text,
  whatsapp             text,
  email                text,
  web                  text,
  razon_social         text,
  cuit                 text,
  condicion_iva        text,
  direccion            text,
  ciudad               text,
  stock_minimo_defecto int not null default 2,
  actualizado          timestamptz not null default now()
);

-- ---------- Productos ----------
create table if not exists productos (
  id          bigint generated by default as identity primary key,
  nombre      text not null,
  categoria   text,
  descripcion text,
  colores     text[] not null default '{}',
  precio      numeric(12,2) not null default 0,
  costo       numeric(12,2) not null default 0,
  estado      text not null default 'Activo'
              check (estado in ('Activo','Pausado','Agotado','Discontinuado')),
  foto_url    text,
  creado      timestamptz not null default now()
);

-- ---------- Stock por producto y color ----------
create table if not exists stock (
  id          bigint generated by default as identity primary key,
  producto_id bigint not null references productos(id) on delete cascade,
  color       text not null default 'Único',
  cantidad    int not null default 0,
  minimo      int,               -- si queda vacío se usa el mínimo de Configuración
  unique (producto_id, color)
);

-- ---------- Clientes ----------
create table if not exists clientes (
  id           bigint generated by default as identity primary key,
  nombre       text not null,
  telefono     text,
  email        text,
  instagram    text,
  canal_origen text,
  ciudad       text,
  notas        text,
  creado       timestamptz not null default now()
);

-- ---------- Eventos ----------
create table if not exists eventos (
  id             bigint generated by default as identity primary key,
  nombre         text not null,
  fecha          date not null,
  hora           text,
  lugar          text,
  descripcion    text,
  precio_entrada numeric(12,2) not null default 0,
  cupos          int not null default 0,
  inscriptos     int not null default 0,
  presupuesto    numeric(12,2) not null default 0,
  estado         text not null default 'Planificando'
                 check (estado in ('Planificando','Confirmado','Realizado','Cancelado')),
  resultado      text,
  creado         timestamptz not null default now()
);

create table if not exists evento_tareas (
  id          bigint generated by default as identity primary key,
  evento_id   bigint not null references eventos(id) on delete cascade,
  tarea       text not null,
  responsable text,
  hecha       boolean not null default false,
  creado      timestamptz not null default now()
);

create table if not exists evento_colaboradores (
  id        bigint generated by default as identity primary key,
  evento_id bigint not null references eventos(id) on delete cascade,
  nombre    text not null,
  rol       text,
  contacto  text,
  aporte    text,
  creado    timestamptz not null default now()
);

-- ---------- Ventas / Pedidos ----------
create table if not exists pedidos (
  id          bigint generated by default as identity primary key,
  fecha       date not null default current_date,
  cliente_id  bigint references clientes(id) on delete set null,
  canal       text not null default 'Instagram'
              check (canal in ('Instagram','Web','WhatsApp','Evento','Otro')),
  estado      text not null default 'Pendiente'
              check (estado in ('Pendiente','Pagado','Preparando','Enviado','Entregado','Cancelado')),
  evento_id   bigint references eventos(id) on delete set null,
  subtotal    numeric(12,2) not null default 0,   -- lo calcula la base sola
  descuento   numeric(12,2) not null default 0,
  envio       numeric(12,2) not null default 0,
  total       numeric(12,2) generated always as (subtotal - descuento + envio) stored,
  notas       text,
  creado      timestamptz not null default now(),
  actualizado timestamptz not null default now()
);

create table if not exists pedido_items (
  id              bigint generated by default as identity primary key,
  pedido_id       bigint not null references pedidos(id) on delete cascade,
  producto_id     bigint references productos(id) on delete set null,
  descripcion     text,            -- nombre del producto al momento de la venta
  color           text not null default 'Único',
  cantidad        int not null check (cantidad > 0),
  precio_unitario numeric(12,2) not null default 0,
  costo_unitario  numeric(12,2) not null default 0
);

-- ---------- Movimientos de stock (entradas, salidas, ajustes) ----------
create table if not exists movimientos_stock (
  id             bigint generated by default as identity primary key,
  fecha          date not null default current_date,
  producto_id    bigint not null references productos(id) on delete cascade,
  color          text not null default 'Único',
  tipo           text not null check (tipo in ('entrada','salida','ajuste')),
  cantidad       int not null,     -- entrada/salida: positivo · ajuste: puede ser negativo
  motivo         text,
  pedido_id      bigint,           -- solo informativo
  pedido_item_id bigint references pedido_items(id) on delete cascade,
  creado         timestamptz not null default now(),
  check (tipo = 'ajuste' or cantidad > 0)
);

-- ---------- Proveedores ----------
create table if not exists proveedores (
  id               bigint generated by default as identity primary key,
  nombre           text not null,
  que_provee       text,
  contacto         text,
  telefono         text,
  email            text,
  instagram        text,
  tiempo_entrega   text,
  condiciones_pago text,
  notas            text,
  creado           timestamptz not null default now()
);

-- ---------- Finanzas (ingresos y egresos que no son ventas) ----------
create table if not exists movimientos_financieros (
  id           bigint generated by default as identity primary key,
  fecha        date not null default current_date,
  tipo         text not null check (tipo in ('ingreso','egreso')),
  categoria    text not null default 'Otros',
  descripcion  text,
  monto        numeric(12,2) not null check (monto >= 0),
  medio_pago   text,
  evento_id    bigint references eventos(id) on delete set null,
  proveedor_id bigint references proveedores(id) on delete set null,
  creado       timestamptz not null default now()
);

-- ---------- Contenido / Marketing ----------
create table if not exists pilares_contenido (
  id          bigint generated by default as identity primary key,
  nombre      text not null,
  descripcion text,
  color       text default '#9cc9e8',
  creado      timestamptz not null default now()
);

create table if not exists publicaciones (
  id          bigint generated by default as identity primary key,
  fecha       date not null,
  red         text not null default 'Instagram',
  formato     text not null default 'Post',
  pilar_id    bigint references pilares_contenido(id) on delete set null,
  titulo      text not null,
  texto       text,
  estado      text not null default 'Idea'
              check (estado in ('Idea','En preparación','Programada','Publicada')),
  link        text,
  alcance     int,
  me_gusta    int,
  comentarios int,
  guardados   int,
  creado      timestamptz not null default now()
);

create table if not exists ideas_contenido (
  id          bigint generated by default as identity primary key,
  titulo      text not null,
  descripcion text,
  pilar_id    bigint references pilares_contenido(id) on delete set null,
  formato     text,
  prioridad   text not null default 'Media' check (prioridad in ('Alta','Media','Baja')),
  usada       boolean not null default false,
  creado      timestamptz not null default now()
);

create table if not exists metricas_instagram (
  id              bigint generated by default as identity primary key,
  fecha           date not null,      -- usamos el día 1 de cada mes
  seguidores      int not null default 0,
  alcance         int,
  interacciones   int,
  visitas_perfil  int,
  clics_link      int,
  notas           text,
  creado          timestamptz not null default now()
);

-- ---------- Equipo ----------
create table if not exists personas (
  id       bigint generated by default as identity primary key,
  nombre   text not null,
  rol      text,
  email    text,
  telefono text,
  activa   boolean not null default true,
  creado   timestamptz not null default now()
);

create table if not exists tareas (
  id           bigint generated by default as identity primary key,
  titulo       text not null,
  descripcion  text,
  persona_id   bigint references personas(id) on delete set null,
  area         text,
  prioridad    text not null default 'Media' check (prioridad in ('Alta','Media','Baja')),
  fecha_limite date,
  estado       text not null default 'Pendiente' check (estado in ('Pendiente','En curso','Hecha')),
  creado       timestamptz not null default now()
);

-- ---------- Insumos y packaging ----------
create table if not exists insumos (
  id             bigint generated by default as identity primary key,
  codigo         text,
  nombre         text not null,
  tipo           text default 'Packaging',
  stock          int not null default 0,
  costo_unitario numeric(12,2),
  minimo         int,               -- si queda vacío se usa 3
  proveedor_id   bigint references proveedores(id) on delete set null,
  observaciones  text,
  creado         timestamptz not null default now()
);

-- ---------- Agregados (versión 2: datos reales del Excel) ----------
alter table productos add column if not exists codigo text;
alter table pedidos   add column if not exists medio_pago text;
alter table pedidos   alter column canal set default 'Presencial';
alter table pedidos   drop constraint if exists pedidos_canal_check;
alter table pedidos   add constraint pedidos_canal_check
  check (canal in ('Presencial','Instagram','Web','WhatsApp','Evento','Otro'));

-- Índices para que las búsquedas sean rápidas
create index if not exists idx_stock_producto      on stock(producto_id);
create index if not exists idx_items_pedido        on pedido_items(pedido_id);
create index if not exists idx_items_producto      on pedido_items(producto_id);
create index if not exists idx_mov_producto        on movimientos_stock(producto_id, color);
create index if not exists idx_mov_item            on movimientos_stock(pedido_item_id);
create index if not exists idx_pedidos_fecha       on pedidos(fecha);
create index if not exists idx_pedidos_cliente     on pedidos(cliente_id);
create index if not exists idx_fin_fecha           on movimientos_financieros(fecha);
create index if not exists idx_publicaciones_fecha on publicaciones(fecha);
create index if not exists idx_tareas_persona      on tareas(persona_id);

-- La fila única de configuración
insert into configuracion (id) values (1) on conflict (id) do nothing;
