-- =====================================================================
-- SINAN ERP · 10 - COSTO DETALLADO Y PACKAGING POR PRODUCTO
-- · Cada producto guarda: costo base + otros gastos (+ packaging) = costo total
-- · Cada producto tiene su "receta" de packaging (qué insumos lleva y cuántos)
-- · Al vender, los insumos de la receta se descuentan solos del stock de
--   insumos; si la venta se cancela o se borra, vuelven.
-- No borra datos. Se puede volver a correr.
-- =====================================================================

alter table productos add column if not exists costo_base numeric(12,2);
alter table productos add column if not exists costo_extra numeric(12,2) not null default 0;
alter table productos add column if not exists costo_extra_detalle text;

create table if not exists producto_insumos (
  id          bigint generated by default as identity primary key,
  producto_id bigint not null references productos(id) on delete cascade,
  insumo_id   bigint not null references insumos(id) on delete cascade,
  cantidad    int not null default 1 check (cantidad > 0),
  unique (producto_id, insumo_id)
);
create index if not exists idx_producto_insumos_producto on producto_insumos(producto_id);

alter table producto_insumos enable row level security;
drop policy if exists "solo usuarios logueados" on producto_insumos;
create policy "solo usuarios logueados" on producto_insumos for all to authenticated using (true) with check (true);
revoke all on producto_insumos from anon;
grant select, insert, update, delete on producto_insumos to authenticated;
grant usage, select on all sequences in schema public to authenticated;

-- Los movimientos de stock que vienen de una venta también mueven los insumos del packaging
create or replace function trg_movimientos_stock()
returns trigger language plpgsql set search_path = public as $$
begin
  if tg_op in ('UPDATE','DELETE') then
    perform aplicar_stock(old.producto_id, old.color, -delta_movimiento(old.tipo, old.cantidad), false);
    if old.pedido_item_id is not null then   -- devuelve el packaging
      update insumos i set stock = i.stock + pi.cantidad * old.cantidad
        from producto_insumos pi where pi.producto_id = old.producto_id and pi.insumo_id = i.id;
    end if;
  end if;
  if tg_op in ('INSERT','UPDATE') then
    perform aplicar_stock(new.producto_id, new.color, delta_movimiento(new.tipo, new.cantidad), true);
    if new.pedido_item_id is not null then   -- descuenta el packaging
      update insumos i set stock = i.stock - pi.cantidad * new.cantidad
        from producto_insumos pi where pi.producto_id = new.producto_id and pi.insumo_id = i.id;
    end if;
    return new;
  end if;
  return old;
end $$;

-- Completar el costo detallado de los productos que todavía no lo tienen
-- (costo base y gasto extra del Excel de inventario 2026)
update productos p set costo_base = x.base, costo_extra = x.extra, costo_extra_detalle = 'Gasto extra (según Excel)'
  from (values
    ('Bolso Kala', 26000, 1130), ('Bolso Cielo', 19000, 1130), ('Bolso Rufina', 22000, 1330), ('Tote Bag Lienzo', 3000, 2000),
    ('Bandolera Anitta', 12000, 1000), ('Mini bag Lucy', 14000, 2000), ('Cartera Venice', 20000, 1000), ('Mochila Zafira', 15900, 1130),
    ('Mochila Ivana', 29700, 7200), ('Mochila Lira', 25800, 7200), ('Billetera Kaira', 7590, 1200), ('Billetera Pocket', 10500, 2150),
    ('Billetera Kira', 7590, 1200), ('Llavero Lua (perrita con cadena)', 2350, 1400), ('Llavero Doni', 2500, 1400), ('Llavero Panchi', 3000, 180),
    ('Scrunchie de Satén', 1200, 400), ('Funda de Satén', 3400, 1100), ('Arito corazón', 4500, 900), ('Neceser', 4500, 900),
    ('Neceser Lua', 9900, 1210), ('Medias elemento', 1750, 190), ('Scrunchie de Satén x mayor', 1750, 175), ('Funda de Satén x mayor', 4450, 175),
    ('Cofias simples', 3831, 175), ('Scrunchie de Satén PREMIUM x mayor', 2600, 175), ('Funda de Satén PREMIUM x mayor', 5250, 175), ('Cofias simples PREMIUM', 3831, 175)
  ) as x(nombre, base, extra)
 where p.nombre = x.nombre and p.costo_base is null and p.costo = x.base + x.extra;

-- Los demás: todo el costo como costo base
update productos set costo_base = costo, costo_extra = 0 where costo_base is null;
