-- =====================================================================
-- SINAN ERP · 11 - NOTAS RÁPIDAS DE LA AGENDA (desde el Inicio)
-- Ej: "18/10 · Día de la Madre". No borra datos. Se puede volver a correr.
-- =====================================================================
create table if not exists agenda_notas (
  id     bigint generated by default as identity primary key,
  fecha  date not null,
  texto  text not null,
  creado timestamptz not null default now()
);
create index if not exists idx_agenda_notas_fecha on agenda_notas(fecha);

alter table agenda_notas enable row level security;
drop policy if exists "solo usuarios logueados" on agenda_notas;
create policy "solo usuarios logueados" on agenda_notas for all to authenticated using (true) with check (true);
revoke all on agenda_notas from anon;
grant select, insert, update, delete on agenda_notas to authenticated;
grant usage, select on all sequences in schema public to authenticated;
revoke usage, select on all sequences in schema public from anon;
