-- =====================================================================
-- SINAN ERP · 12 - GASTOS FIJOS MENSUALES (Finanzas → Gastos operativos)
-- · gastos_fijos: cada herramienta, su monto para Sinan, día de vencimiento y estado
--     Activo     = se descuenta de caja (se carga como gasto en Finanzas)
--     Registrado = no se descuenta (se acumula como "Deuda operativa Sinan")
--     Inactivo   = no suma ni avisa
-- · gastos_fijos_mes: lo que quedó anotado cada mes (uno por herramienta y mes)
-- No borra datos. Se puede volver a correr.
-- =====================================================================
create table if not exists gastos_fijos (
  id              bigint generated by default as identity primary key,
  nombre          text not null,
  monto           numeric(12,2) not null check (monto >= 0),
  dia_vencimiento int not null default 10 check (dia_vencimiento between 1 and 28),
  estado          text not null default 'Activo' check (estado in ('Activo','Registrado','Inactivo')),
  desde           text not null default to_char(current_date, 'YYYY-MM'),   -- primer mes que cuenta
  notas           text,
  creado          timestamptz not null default now()
);

create table if not exists gastos_fijos_mes (
  id            bigint generated by default as identity primary key,
  gasto_fijo_id bigint not null references gastos_fijos(id) on delete cascade,
  mes           text not null,                       -- 'AAAA-MM'
  monto         numeric(12,2) not null,
  modo          text not null check (modo in ('descuenta','registra')),
  movimiento_id bigint references movimientos_financieros(id) on delete set null,
  creado        timestamptz not null default now(),
  unique (gasto_fijo_id, mes)
);

do $$
declare t text;
begin
  foreach t in array array['gastos_fijos','gastos_fijos_mes'] loop
    execute format('alter table public.%I enable row level security', t);
    execute format('drop policy if exists "solo usuarios logueados" on public.%I', t);
    execute format('create policy "solo usuarios logueados" on public.%I for all to authenticated using (true) with check (true)', t);
    execute format('revoke all on public.%I from anon', t);
    execute format('grant select, insert, update, delete on public.%I to authenticated', t);
  end loop;
end $$;
grant usage, select on all sequences in schema public to authenticated;
revoke usage, select on all sequences in schema public from anon;

-- Los tres gastos fijos de hoy (solo si la tabla está vacía)
insert into gastos_fijos (nombre, monto, dia_vencimiento, estado, desde)
select * from (values ('CapCut', 4000, 10, 'Activo', '2026-10'), ('Claude', 10000, 10, 'Activo', '2026-10'), ('Google Fotos', 2833, 10, 'Activo', '2026-10')) v
where not exists (select 1 from gastos_fijos);
