-- =====================================================================
-- SINAN ERP · 13 - INSCRIPTOS DE CADA EVENTO
-- Nombre, fecha de nacimiento, monto abonado, fecha de inscripción y
-- estado de pago (Pendiente / Confirmado). No borra datos.
-- =====================================================================
create table if not exists evento_inscriptos (
  id                bigint generated by default as identity primary key,
  evento_id         bigint not null references eventos(id) on delete cascade,
  nombre            text not null,
  fecha_nacimiento  date,
  monto             numeric(12,2) not null default 0 check (monto >= 0),
  fecha_inscripcion date not null default current_date,
  estado_pago       text not null default 'Pendiente' check (estado_pago in ('Pendiente','Confirmado')),
  notas             text,
  creado            timestamptz not null default now()
);
create index if not exists idx_inscriptos_evento on evento_inscriptos(evento_id);

alter table evento_inscriptos enable row level security;
drop policy if exists "solo usuarios logueados" on evento_inscriptos;
create policy "solo usuarios logueados" on evento_inscriptos for all to authenticated using (true) with check (true);
revoke all on evento_inscriptos from anon;
grant select, insert, update, delete on evento_inscriptos to authenticated;
grant usage, select on all sequences in schema public to authenticated;
revoke usage, select on all sequences in schema public from anon;
