-- SINAN ERP · DATOS REALES DEL EXCEL (¡borra y recarga todo!)


-- =====================================================================
-- SINAN ERP · 01 - TABLAS
-- Crea todas las tablas del sistema y sus relaciones.
-- Se puede correr más de una vez: si la tabla ya existe, no la toca.
-- =====================================================================

-- ---------- Configuración (una sola fila con los datos de la marca) ----------
create table if not exists configuracion (
  id                   int primary key default 1 check (id = 1),
  nombre_marca         text not null default 'Sinan',
  frase                text default 'Movete a tu ritmo',
  descripcion          text,
  instagram            text,
  tiktok               text,
  whatsapp             text,
  email                text,
  web                  text,
  razon_social         text,
  cuit                 text,
  condicion_iva        text,
  direccion            text,
  ciudad               text,
  stock_minimo_defecto int not null default 2,
  actualizado          timestamptz not null default now()
);

-- ---------- Productos ----------
create table if not exists productos (
  id          bigint generated by default as identity primary key,
  nombre      text not null,
  categoria   text,
  descripcion text,
  colores     text[] not null default '{}',
  precio      numeric(12,2) not null default 0,
  costo       numeric(12,2) not null default 0,
  estado      text not null default 'Activo'
              check (estado in ('Activo','Pausado','Agotado','Discontinuado')),
  foto_url    text,
  creado      timestamptz not null default now()
);

-- ---------- Stock por producto y color ----------
create table if not exists stock (
  id          bigint generated by default as identity primary key,
  producto_id bigint not null references productos(id) on delete cascade,
  color       text not null default 'Único',
  cantidad    int not null default 0,
  minimo      int,               -- si queda vacío se usa el mínimo de Configuración
  unique (producto_id, color)
);

-- ---------- Clientes ----------
create table if not exists clientes (
  id           bigint generated by default as identity primary key,
  nombre       text not null,
  telefono     text,
  email        text,
  instagram    text,
  canal_origen text,
  ciudad       text,
  notas        text,
  creado       timestamptz not null default now()
);

-- ---------- Eventos ----------
create table if not exists eventos (
  id             bigint generated by default as identity primary key,
  nombre         text not null,
  fecha          date not null,
  hora           text,
  lugar          text,
  descripcion    text,
  precio_entrada numeric(12,2) not null default 0,
  cupos          int not null default 0,
  inscriptos     int not null default 0,
  presupuesto    numeric(12,2) not null default 0,
  estado         text not null default 'Planificando'
                 check (estado in ('Planificando','Confirmado','Realizado','Cancelado')),
  resultado      text,
  creado         timestamptz not null default now()
);

create table if not exists evento_tareas (
  id          bigint generated by default as identity primary key,
  evento_id   bigint not null references eventos(id) on delete cascade,
  tarea       text not null,
  responsable text,
  hecha       boolean not null default false,
  creado      timestamptz not null default now()
);

create table if not exists evento_colaboradores (
  id        bigint generated by default as identity primary key,
  evento_id bigint not null references eventos(id) on delete cascade,
  nombre    text not null,
  rol       text,
  contacto  text,
  aporte    text,
  creado    timestamptz not null default now()
);

-- ---------- Ventas / Pedidos ----------
create table if not exists pedidos (
  id          bigint generated by default as identity primary key,
  fecha       date not null default current_date,
  cliente_id  bigint references clientes(id) on delete set null,
  canal       text not null default 'Instagram'
              check (canal in ('Instagram','Web','WhatsApp','Evento','Otro')),
  estado      text not null default 'Pendiente'
              check (estado in ('Pendiente','Pagado','Preparando','Enviado','Entregado','Cancelado')),
  evento_id   bigint references eventos(id) on delete set null,
  subtotal    numeric(12,2) not null default 0,   -- lo calcula la base sola
  descuento   numeric(12,2) not null default 0,
  envio       numeric(12,2) not null default 0,
  total       numeric(12,2) generated always as (subtotal - descuento + envio) stored,
  notas       text,
  creado      timestamptz not null default now(),
  actualizado timestamptz not null default now()
);

create table if not exists pedido_items (
  id              bigint generated by default as identity primary key,
  pedido_id       bigint not null references pedidos(id) on delete cascade,
  producto_id     bigint references productos(id) on delete set null,
  descripcion     text,            -- nombre del producto al momento de la venta
  color           text not null default 'Único',
  cantidad        int not null check (cantidad > 0),
  precio_unitario numeric(12,2) not null default 0,
  costo_unitario  numeric(12,2) not null default 0
);

-- ---------- Movimientos de stock (entradas, salidas, ajustes) ----------
create table if not exists movimientos_stock (
  id             bigint generated by default as identity primary key,
  fecha          date not null default current_date,
  producto_id    bigint not null references productos(id) on delete cascade,
  color          text not null default 'Único',
  tipo           text not null check (tipo in ('entrada','salida','ajuste')),
  cantidad       int not null,     -- entrada/salida: positivo · ajuste: puede ser negativo
  motivo         text,
  pedido_id      bigint,           -- solo informativo
  pedido_item_id bigint references pedido_items(id) on delete cascade,
  creado         timestamptz not null default now(),
  check (tipo = 'ajuste' or cantidad > 0)
);

-- ---------- Proveedores ----------
create table if not exists proveedores (
  id               bigint generated by default as identity primary key,
  nombre           text not null,
  que_provee       text,
  contacto         text,
  telefono         text,
  email            text,
  instagram        text,
  tiempo_entrega   text,
  condiciones_pago text,
  notas            text,
  creado           timestamptz not null default now()
);

-- ---------- Finanzas (ingresos y egresos que no son ventas) ----------
create table if not exists movimientos_financieros (
  id           bigint generated by default as identity primary key,
  fecha        date not null default current_date,
  tipo         text not null check (tipo in ('ingreso','egreso')),
  categoria    text not null default 'Otros',
  descripcion  text,
  monto        numeric(12,2) not null check (monto >= 0),
  medio_pago   text,
  evento_id    bigint references eventos(id) on delete set null,
  proveedor_id bigint references proveedores(id) on delete set null,
  creado       timestamptz not null default now()
);

-- ---------- Contenido / Marketing ----------
create table if not exists pilares_contenido (
  id          bigint generated by default as identity primary key,
  nombre      text not null,
  descripcion text,
  color       text default '#9cc9e8',
  creado      timestamptz not null default now()
);

create table if not exists publicaciones (
  id          bigint generated by default as identity primary key,
  fecha       date not null,
  red         text not null default 'Instagram',
  formato     text not null default 'Post',
  pilar_id    bigint references pilares_contenido(id) on delete set null,
  titulo      text not null,
  texto       text,
  estado      text not null default 'Idea'
              check (estado in ('Idea','En preparación','Programada','Publicada')),
  link        text,
  alcance     int,
  me_gusta    int,
  comentarios int,
  guardados   int,
  creado      timestamptz not null default now()
);

create table if not exists ideas_contenido (
  id          bigint generated by default as identity primary key,
  titulo      text not null,
  descripcion text,
  pilar_id    bigint references pilares_contenido(id) on delete set null,
  formato     text,
  prioridad   text not null default 'Media' check (prioridad in ('Alta','Media','Baja')),
  usada       boolean not null default false,
  creado      timestamptz not null default now()
);

create table if not exists metricas_instagram (
  id              bigint generated by default as identity primary key,
  fecha           date not null,      -- usamos el día 1 de cada mes
  seguidores      int not null default 0,
  alcance         int,
  interacciones   int,
  visitas_perfil  int,
  clics_link      int,
  notas           text,
  creado          timestamptz not null default now()
);

-- ---------- Equipo ----------
create table if not exists personas (
  id       bigint generated by default as identity primary key,
  nombre   text not null,
  rol      text,
  email    text,
  telefono text,
  activa   boolean not null default true,
  creado   timestamptz not null default now()
);

create table if not exists tareas (
  id           bigint generated by default as identity primary key,
  titulo       text not null,
  descripcion  text,
  persona_id   bigint references personas(id) on delete set null,
  area         text,
  prioridad    text not null default 'Media' check (prioridad in ('Alta','Media','Baja')),
  fecha_limite date,
  estado       text not null default 'Pendiente' check (estado in ('Pendiente','En curso','Hecha')),
  creado       timestamptz not null default now()
);

-- ---------- Insumos y packaging ----------
create table if not exists insumos (
  id             bigint generated by default as identity primary key,
  codigo         text,
  nombre         text not null,
  tipo           text default 'Packaging',
  stock          int not null default 0,
  costo_unitario numeric(12,2),
  minimo         int,               -- si queda vacío se usa 3
  proveedor_id   bigint references proveedores(id) on delete set null,
  observaciones  text,
  creado         timestamptz not null default now()
);

-- ---------- Agregados (versión 2: datos reales del Excel) ----------
alter table productos add column if not exists codigo text;
alter table pedidos   add column if not exists medio_pago text;
alter table pedidos   alter column canal set default 'Presencial';
alter table pedidos   drop constraint if exists pedidos_canal_check;
alter table pedidos   add constraint pedidos_canal_check
  check (canal in ('Presencial','Feria','Instagram','Web','WhatsApp','Evento','Otro'));

-- ---------- Agregados (versión 3: ferias, CRM y marketing) ----------
-- Eventos: tipo (encuentro, feria…) y costo del puesto en ferias
alter table eventos add column if not exists tipo text not null default 'Encuentro';
alter table eventos drop constraint if exists eventos_tipo_check;
alter table eventos add constraint eventos_tipo_check check (tipo in ('Encuentro','Feria','Taller','Otro'));
alter table eventos add column if not exists costo_puesto numeric(12,2) not null default 0;

-- Clientes como CRM
alter table clientes add column if not exists fecha_nacimiento date;
alter table clientes add column if not exists etiquetas text[] not null default '{}';
alter table clientes add column if not exists intereses text;
alter table clientes add column if not exists direccion text;
alter table clientes add column if not exists proximo_contacto date;

create table if not exists cliente_interacciones (
  id         bigint generated by default as identity primary key,
  cliente_id bigint not null references clientes(id) on delete cascade,
  fecha      date not null default current_date,
  tipo       text not null default 'WhatsApp',
  nota       text not null,
  creado     timestamptz not null default now()
);
create index if not exists idx_interacciones_cliente on cliente_interacciones(cliente_id);

-- Marketing: estrategia (una sola fila), objetivos y campañas
create table if not exists estrategia_mkt (
  id                int primary key default 1 check (id = 1),
  objetivo_general  text,
  publico_objetivo  text,
  propuesta_valor   text,
  tono              text,
  diferenciales     text,
  canales           text,
  competencia       text,
  notas             text,
  actualizado       timestamptz not null default now()
);
insert into estrategia_mkt (id) values (1) on conflict (id) do nothing;

create table if not exists objetivos_mkt (
  id           bigint generated by default as identity primary key,
  objetivo     text not null,
  metrica      text,
  meta         numeric(14,2),
  actual       numeric(14,2),
  fecha_limite date,
  estado       text not null default 'En curso' check (estado in ('Pendiente','En curso','Logrado','No logrado')),
  creado       timestamptz not null default now()
);

create table if not exists campanas (
  id           bigint generated by default as identity primary key,
  nombre       text not null,
  tipo         text,
  fecha_inicio date,
  fecha_fin    date,
  canal        text,
  objetivo     text,
  presupuesto  numeric(12,2) not null default 0,
  resultado    text,
  estado       text not null default 'Planificada' check (estado in ('Planificada','Activa','Terminada','Cancelada')),
  creado       timestamptz not null default now()
);
alter table movimientos_financieros add column if not exists campana_id bigint references campanas(id) on delete set null;

-- Índices para que las búsquedas sean rápidas
create index if not exists idx_stock_producto      on stock(producto_id);
create index if not exists idx_items_pedido        on pedido_items(pedido_id);
create index if not exists idx_items_producto      on pedido_items(producto_id);
create index if not exists idx_mov_producto        on movimientos_stock(producto_id, color);
create index if not exists idx_mov_item            on movimientos_stock(pedido_item_id);
create index if not exists idx_pedidos_fecha       on pedidos(fecha);
create index if not exists idx_pedidos_cliente     on pedidos(cliente_id);
create index if not exists idx_fin_fecha           on movimientos_financieros(fecha);
create index if not exists idx_publicaciones_fecha on publicaciones(fecha);
create index if not exists idx_tareas_persona      on tareas(persona_id);

-- La fila única de configuración
insert into configuracion (id) values (1) on conflict (id) do nothing;


-- =====================================================================
-- SINAN ERP · 02 - AUTOMATISMOS
-- Cosas que la base hace sola:
--   · Mantener el stock al día con cada entrada / salida / venta
--   · Calcular el total de cada pedido
--   · Devolver el stock si un pedido se cancela o se borra
--   · Crear las filas de stock de cada color al cargar un producto
-- =====================================================================

-- Cuánto suma o resta un movimiento
create or replace function delta_movimiento(p_tipo text, p_cantidad int)
returns int language sql immutable set search_path = public as $$
  select case p_tipo when 'salida' then -p_cantidad else p_cantidad end;
$$;

-- Suma (o resta) unidades al stock de un producto/color
create or replace function aplicar_stock(p_producto bigint, p_color text, p_delta int, p_crear boolean)
returns void language plpgsql set search_path = public as $$
begin
  update stock set cantidad = cantidad + p_delta
   where producto_id = p_producto and color = p_color;
  if not found and p_crear then
    insert into stock (producto_id, color, cantidad) values (p_producto, p_color, p_delta)
    on conflict (producto_id, color) do update set cantidad = stock.cantidad + excluded.cantidad;
  end if;
end $$;

-- Cada movimiento de stock actualiza la tabla stock
create or replace function trg_movimientos_stock()
returns trigger language plpgsql set search_path = public as $$
begin
  if tg_op in ('UPDATE','DELETE') then
    perform aplicar_stock(old.producto_id, old.color, -delta_movimiento(old.tipo, old.cantidad), false);
  end if;
  if tg_op in ('INSERT','UPDATE') then
    perform aplicar_stock(new.producto_id, new.color, delta_movimiento(new.tipo, new.cantidad), true);
    return new;
  end if;
  return old;
end $$;

drop trigger if exists movimientos_stock_sync on movimientos_stock;
create trigger movimientos_stock_sync
  after insert or update of producto_id, color, tipo, cantidad or delete on movimientos_stock
  for each row execute function trg_movimientos_stock();

-- Cada ítem vendido genera su salida de stock y recalcula el total del pedido
create or replace function trg_pedido_items()
returns trigger language plpgsql set search_path = public as $$
declare
  v_pedido_id bigint;
  v_pedido    pedidos%rowtype;
begin
  if tg_op = 'DELETE' then v_pedido_id := old.pedido_id; else v_pedido_id := new.pedido_id; end if;

  if tg_op in ('UPDATE','DELETE') then
    delete from movimientos_stock where pedido_item_id = old.id;
  end if;

  if tg_op in ('INSERT','UPDATE') then
    select * into v_pedido from pedidos where id = new.pedido_id;
    if new.producto_id is not null and v_pedido.estado <> 'Cancelado' then
      insert into movimientos_stock (fecha, producto_id, color, tipo, cantidad, motivo, pedido_id, pedido_item_id)
      values (v_pedido.fecha, new.producto_id, new.color, 'salida', new.cantidad,
              'Venta · pedido #' || new.pedido_id, new.pedido_id, new.id);
    end if;
  end if;

  update pedidos
     set subtotal = (select coalesce(sum(cantidad * precio_unitario), 0) from pedido_items where pedido_id = v_pedido_id)
   where id = v_pedido_id;
  return null;
end $$;

drop trigger if exists pedido_items_sync on pedido_items;
create trigger pedido_items_sync
  after insert or update or delete on pedido_items
  for each row execute function trg_pedido_items();

-- Marca la fecha de última actualización de un pedido
create or replace function trg_pedidos_actualizado()
returns trigger language plpgsql set search_path = public as $$
begin
  -- si se cambia a mano la fecha de actualización se respeta; si no, se pone "ahora"
  if new.actualizado is not distinct from old.actualizado then
    new.actualizado := now();
  end if;
  return new;
end $$;

drop trigger if exists pedidos_actualizado on pedidos;
create trigger pedidos_actualizado
  before update on pedidos
  for each row execute function trg_pedidos_actualizado();

-- Si un pedido se cancela devuelve el stock; si se "des-cancela" lo vuelve a descontar
create or replace function trg_pedidos_estado()
returns trigger language plpgsql set search_path = public as $$
begin
  if new.estado = 'Cancelado' and old.estado <> 'Cancelado' then
    delete from movimientos_stock where pedido_id = new.id and pedido_item_id is not null;
  elsif old.estado = 'Cancelado' and new.estado <> 'Cancelado' then
    insert into movimientos_stock (fecha, producto_id, color, tipo, cantidad, motivo, pedido_id, pedido_item_id)
    select new.fecha, i.producto_id, i.color, 'salida', i.cantidad, 'Venta · pedido #' || new.id, new.id, i.id
      from pedido_items i
     where i.pedido_id = new.id and i.producto_id is not null;
  end if;
  return null;
end $$;

drop trigger if exists pedidos_estado on pedidos;
create trigger pedidos_estado
  after update of estado on pedidos
  for each row execute function trg_pedidos_estado();

-- Al cargar o editar un producto se crea una fila de stock por cada color
create or replace function trg_productos_colores()
returns trigger language plpgsql set search_path = public as $$
begin
  insert into stock (producto_id, color, cantidad)
  select new.id, c, 0
    from unnest(case when coalesce(array_length(new.colores, 1), 0) = 0
                     then array['Único'] else new.colores end) as c
  on conflict (producto_id, color) do nothing;
  return null;
end $$;

drop trigger if exists productos_colores on productos;
create trigger productos_colores
  after insert or update of colores on productos
  for each row execute function trg_productos_colores();

-- Guarda un pedido completo (cabecera + productos) de una sola vez.
-- Si algo falla no se guarda nada a medias.
-- Al editar un pedido viejo se conserva el costo que tenía cada producto en ese momento.
create or replace function guardar_pedido(p_pedido jsonb, p_items jsonb)
returns bigint language plpgsql set search_path = public as $$
declare
  v_id     bigint;
  v_costos jsonb := '{}';
begin
  if p_items is null or jsonb_array_length(p_items) = 0 then
    raise exception 'El pedido tiene que tener al menos un producto';
  end if;

  if coalesce(p_pedido->>'id', '') = '' then
    insert into pedidos (fecha, cliente_id, canal, estado, medio_pago, evento_id, descuento, envio, notas)
    values (
      coalesce((p_pedido->>'fecha')::date, current_date),
      nullif(p_pedido->>'cliente_id', '')::bigint,
      coalesce(p_pedido->>'canal', 'Presencial'),
      coalesce(p_pedido->>'estado', 'Pendiente'),
      nullif(p_pedido->>'medio_pago', ''),
      nullif(p_pedido->>'evento_id', '')::bigint,
      coalesce(nullif(p_pedido->>'descuento', '')::numeric, 0),
      coalesce(nullif(p_pedido->>'envio', '')::numeric, 0),
      p_pedido->>'notas'
    ) returning id into v_id;
  else
    v_id := (p_pedido->>'id')::bigint;
    select coalesce(jsonb_object_agg(producto_id || '|' || color, costo_unitario), '{}')
      into v_costos from pedido_items where pedido_id = v_id and producto_id is not null;
    delete from pedido_items where pedido_id = v_id;   -- devuelve el stock de los ítems viejos
    update pedidos set
      fecha      = coalesce((p_pedido->>'fecha')::date, fecha),
      cliente_id = nullif(p_pedido->>'cliente_id', '')::bigint,
      canal      = coalesce(p_pedido->>'canal', canal),
      estado     = coalesce(p_pedido->>'estado', estado),
      medio_pago = nullif(p_pedido->>'medio_pago', ''),
      evento_id  = nullif(p_pedido->>'evento_id', '')::bigint,
      descuento  = coalesce(nullif(p_pedido->>'descuento', '')::numeric, 0),
      envio      = coalesce(nullif(p_pedido->>'envio', '')::numeric, 0),
      notas      = p_pedido->>'notas'
    where id = v_id;
    if not found then raise exception 'No existe el pedido #%', v_id; end if;
  end if;

  insert into pedido_items (pedido_id, producto_id, descripcion, color, cantidad, precio_unitario, costo_unitario)
  select v_id,
         p.id,
         coalesce(p.nombre, i->>'descripcion'),
         coalesce(nullif(i->>'color', ''), 'Único'),
         (i->>'cantidad')::int,
         coalesce(nullif(i->>'precio_unitario', '')::numeric, p.precio, 0),
         coalesce((v_costos->>(p.id || '|' || coalesce(nullif(i->>'color', ''), 'Único')))::numeric, p.costo, 0)
    from jsonb_array_elements(p_items) as i
    left join productos p on p.id = nullif(i->>'producto_id', '')::bigint;

  return v_id;
end $$;


-- =====================================================================
-- SINAN ERP · 03 - SEGURIDAD
-- · Row Level Security activado en TODAS las tablas
-- · Solo usuarios logueados pueden leer y escribir
-- · Los visitantes anónimos no tienen acceso a nada
-- · Carpeta "fotos" para las imágenes de productos
-- =====================================================================

do $$
declare
  t text;
begin
  foreach t in array array[
    'configuracion','productos','stock','clientes','eventos','evento_tareas',
    'evento_colaboradores','pedidos','pedido_items','movimientos_stock','proveedores',
    'movimientos_financieros','pilares_contenido','publicaciones','ideas_contenido',
    'metricas_instagram','personas','tareas','insumos','cliente_interacciones',
    'estrategia_mkt','objetivos_mkt','campanas'
  ] loop
    execute format('alter table public.%I enable row level security', t);
    execute format('drop policy if exists "solo usuarios logueados" on public.%I', t);
    execute format('create policy "solo usuarios logueados" on public.%I for all to authenticated using (true) with check (true)', t);
    execute format('revoke all on public.%I from anon', t);
    execute format('grant select, insert, update, delete on public.%I to authenticated', t);
  end loop;
end $$;

grant usage, select on all sequences in schema public to authenticated;
revoke usage, select on all sequences in schema public from anon;

-- Las funciones solo las pueden usar usuarios logueados
revoke execute on function guardar_pedido(jsonb, jsonb)               from public, anon;
revoke execute on function aplicar_stock(bigint, text, int, boolean)  from public, anon;
grant  execute on function guardar_pedido(jsonb, jsonb)               to authenticated;
grant  execute on function aplicar_stock(bigint, text, int, boolean)  to authenticated;

-- ---------- Carpeta de fotos de productos ----------
-- Las fotos se pueden ver con su link (para mostrarlas en pantalla),
-- pero solo un usuario logueado puede subir, cambiar o borrar.
-- (si algo de esta parte falla, el resto igual queda instalado)
do $$
begin
  insert into storage.buckets (id, name, public)
  values ('fotos', 'fotos', true)
  on conflict (id) do nothing;

  drop policy if exists "fotos: ver (logueados)"      on storage.objects;
  drop policy if exists "fotos: subir (logueados)"    on storage.objects;
  drop policy if exists "fotos: cambiar (logueados)"  on storage.objects;
  drop policy if exists "fotos: borrar (logueados)"   on storage.objects;

  create policy "fotos: ver (logueados)"     on storage.objects for select to authenticated using (bucket_id = 'fotos');
  create policy "fotos: subir (logueados)"   on storage.objects for insert to authenticated with check (bucket_id = 'fotos');
  create policy "fotos: cambiar (logueados)" on storage.objects for update to authenticated using (bucket_id = 'fotos');
  create policy "fotos: borrar (logueados)"  on storage.objects for delete to authenticated using (bucket_id = 'fotos');
exception when others then
  raise notice 'No se pudo preparar la carpeta de fotos: %', sqlerrm;
end $$;


-- =====================================================================
-- SINAN ERP · 07 - VERSIÓN 4: pasos del pedido, envíos, responsables
--                  y embudo de consultas (clientes potenciales)
-- No borra datos. Se puede volver a correr.
-- =====================================================================

-- ---------- Pedidos: pasos (preparar → entregar → cobrar), envío y responsables ----------
alter table pedidos add column if not exists preparado_at  timestamptz;
alter table pedidos add column if not exists entregado_at  timestamptz;
alter table pedidos add column if not exists cobrado_at    timestamptz;
alter table pedidos add column if not exists envio_metodo  text;
alter table pedidos add column if not exists envio_detalle text;
alter table pedidos add column if not exists responsable_id bigint references personas(id) on delete set null;
alter table pedidos add column if not exists cargado_por   text;

-- Los estados viejos pasan a pasos (sin tocar el stock ni la fecha de actualización)
alter table pedidos drop constraint if exists pedidos_estado_check;
alter table pedidos disable trigger user;
update pedidos set
  preparado_at = case when estado in ('Enviado','Entregado') then coalesce(preparado_at, fecha + time '12:00') else preparado_at end,
  entregado_at = case when estado in ('Enviado','Entregado') then coalesce(entregado_at, fecha + time '12:00') else entregado_at end,
  cobrado_at   = case when estado in ('Pagado','Entregado') then coalesce(cobrado_at, fecha + time '12:00') else cobrado_at end
 where estado in ('Preparando','Enviado','Entregado','Pagado');

-- La etapa se calcula sola a partir de los pasos (salvo "Cancelado")
create or replace function etapa_pedido(p_prep timestamptz, p_entr timestamptz, p_cobr timestamptz)
returns text language sql immutable set search_path = public as $$
  select case
    when p_prep is null then 'Por preparar'
    when p_entr is null then 'Por entregar'
    when p_cobr is null then 'Por cobrar'
    else 'Completado' end;
$$;

update pedidos set estado = etapa_pedido(preparado_at, entregado_at, cobrado_at) where estado <> 'Cancelado';
alter table pedidos enable trigger user;

alter table pedidos alter column estado set default 'Por preparar';
alter table pedidos add constraint pedidos_estado_check
  check (estado in ('Por preparar','Por entregar','Por cobrar','Completado','Cancelado'));

create or replace function trg_pedidos_etapa()
returns trigger language plpgsql set search_path = public as $$
begin
  if new.estado is distinct from 'Cancelado' then
    new.estado := etapa_pedido(new.preparado_at, new.entregado_at, new.cobrado_at);
  end if;
  return new;
end $$;

drop trigger if exists pedidos_etapa on pedidos;
create trigger pedidos_etapa
  before insert or update on pedidos
  for each row execute function trg_pedidos_etapa();

-- guardar_pedido ahora también guarda pasos, envío y responsables
create or replace function guardar_pedido(p_pedido jsonb, p_items jsonb)
returns bigint language plpgsql set search_path = public as $$
declare
  v_id     bigint;
  v_costos jsonb := '{}';
begin
  if p_items is null or jsonb_array_length(p_items) = 0 then
    raise exception 'El pedido tiene que tener al menos un producto';
  end if;

  if coalesce(p_pedido->>'id', '') = '' then
    insert into pedidos (fecha, cliente_id, canal, estado, medio_pago, evento_id, descuento, envio, notas,
                         preparado_at, entregado_at, cobrado_at, envio_metodo, envio_detalle, responsable_id, cargado_por)
    values (
      coalesce((p_pedido->>'fecha')::date, current_date),
      nullif(p_pedido->>'cliente_id', '')::bigint,
      coalesce(p_pedido->>'canal', 'Presencial'),
      case when p_pedido->>'estado' = 'Cancelado' then 'Cancelado' else 'Por preparar' end,
      nullif(p_pedido->>'medio_pago', ''),
      nullif(p_pedido->>'evento_id', '')::bigint,
      coalesce(nullif(p_pedido->>'descuento', '')::numeric, 0),
      coalesce(nullif(p_pedido->>'envio', '')::numeric, 0),
      p_pedido->>'notas',
      nullif(p_pedido->>'preparado_at', '')::timestamptz,
      nullif(p_pedido->>'entregado_at', '')::timestamptz,
      nullif(p_pedido->>'cobrado_at', '')::timestamptz,
      nullif(p_pedido->>'envio_metodo', ''),
      nullif(p_pedido->>'envio_detalle', ''),
      nullif(p_pedido->>'responsable_id', '')::bigint,
      nullif(p_pedido->>'cargado_por', '')
    ) returning id into v_id;
  else
    v_id := (p_pedido->>'id')::bigint;
    select coalesce(jsonb_object_agg(producto_id || '|' || color, costo_unitario), '{}')
      into v_costos from pedido_items where pedido_id = v_id and producto_id is not null;
    delete from pedido_items where pedido_id = v_id;   -- devuelve el stock de los ítems viejos
    update pedidos set
      fecha          = coalesce((p_pedido->>'fecha')::date, fecha),
      cliente_id     = nullif(p_pedido->>'cliente_id', '')::bigint,
      canal          = coalesce(p_pedido->>'canal', canal),
      estado         = case when p_pedido->>'estado' = 'Cancelado' then 'Cancelado' else 'Por preparar' end,
      medio_pago     = nullif(p_pedido->>'medio_pago', ''),
      evento_id      = nullif(p_pedido->>'evento_id', '')::bigint,
      descuento      = coalesce(nullif(p_pedido->>'descuento', '')::numeric, 0),
      envio          = coalesce(nullif(p_pedido->>'envio', '')::numeric, 0),
      notas          = p_pedido->>'notas',
      preparado_at   = nullif(p_pedido->>'preparado_at', '')::timestamptz,
      entregado_at   = nullif(p_pedido->>'entregado_at', '')::timestamptz,
      cobrado_at     = nullif(p_pedido->>'cobrado_at', '')::timestamptz,
      envio_metodo   = nullif(p_pedido->>'envio_metodo', ''),
      envio_detalle  = nullif(p_pedido->>'envio_detalle', ''),
      responsable_id = nullif(p_pedido->>'responsable_id', '')::bigint
    where id = v_id;
    if not found then raise exception 'No existe el pedido #%', v_id; end if;
  end if;

  insert into pedido_items (pedido_id, producto_id, descripcion, color, cantidad, precio_unitario, costo_unitario)
  select v_id,
         p.id,
         coalesce(p.nombre, i->>'descripcion'),
         coalesce(nullif(i->>'color', ''), 'Único'),
         (i->>'cantidad')::int,
         coalesce(nullif(i->>'precio_unitario', '')::numeric, p.precio, 0),
         coalesce((v_costos->>(p.id || '|' || coalesce(nullif(i->>'color', ''), 'Único')))::numeric, p.costo, 0)
    from jsonb_array_elements(p_items) as i
    left join productos p on p.id = nullif(i->>'producto_id', '')::bigint;

  return v_id;
end $$;

revoke execute on function guardar_pedido(jsonb, jsonb) from public, anon;
grant  execute on function guardar_pedido(jsonb, jsonb) to authenticated;

-- ---------- Embudo de consultas (clientes potenciales) ----------
create table if not exists consultas (
  id               bigint generated by default as identity primary key,
  fecha            date not null default current_date,
  nombre           text not null,
  contacto         text,
  canal            text,
  producto_id      bigint references productos(id) on delete set null,
  producto_texto   text,
  color            text,
  cantidad         int not null default 1,
  presupuesto      numeric(12,2),
  etapa            text not null default 'Nueva' check (etapa in ('Nueva','Presupuesto','Ganada','Perdida')),
  presupuesto_at   timestamptz,
  cerrada_at       timestamptz,
  motivo_perdida   text,
  detalle_perdida  text,
  notas            text,
  responsable_id   bigint references personas(id) on delete set null,
  cliente_id       bigint references clientes(id) on delete set null,
  pedido_id        bigint references pedidos(id) on delete set null,
  creado           timestamptz not null default now(),
  actualizado      timestamptz not null default now()
);
create index if not exists idx_consultas_etapa on consultas(etapa);

alter table consultas enable row level security;
drop policy if exists "solo usuarios logueados" on consultas;
create policy "solo usuarios logueados" on consultas for all to authenticated using (true) with check (true);
revoke all on consultas from anon;
grant select, insert, update, delete on consultas to authenticated;
grant usage, select on all sequences in schema public to authenticated;
revoke usage, select on all sequences in schema public from anon;


-- =====================================================================
-- SINAN ERP · 06 - DATOS REALES (desde Sinan_Finanzas_2026_v2.xlsx)
-- ¡ATENCIÓN! Borra todos los datos actuales (los de ejemplo) y carga
-- los reales del Excel: productos, stock, insumos, clientas, ventas,
-- gastos y proveedores. La configuración de la marca no se toca.
-- =====================================================================

truncate table
  pedido_items, pedidos, movimientos_stock, stock, productos, clientes,
  evento_tareas, evento_colaboradores, movimientos_financieros, eventos,
  proveedores, publicaciones, ideas_contenido, pilares_contenido,
  metricas_instagram, tareas, personas, insumos, cliente_interacciones, consultas,
  objetivos_mkt, campanas
restart identity cascade;

-- Ayudante temporal: crea un pedido presencial entregado
create or replace function public._real_pedido(p_fecha date, p_cliente text, p_medio text)
returns bigint language sql set search_path = public as $$
insert into pedidos (fecha, cliente_id, canal, estado, medio_pago, envio_metodo, preparado_at, entregado_at, cobrado_at, creado, actualizado)  values (p_fecha, (select id from clientes where nombre = p_cliente), 'Presencial', 'Completado', p_medio, 'En mano (presencial)',          p_fecha + time '12:00', p_fecha + time '12:00', p_fecha + time '12:00', p_fecha + time '12:00', p_fecha + time '12:00')
  returning id;
$$;

-- Ayudante temporal: agrega un producto al pedido, con la ganancia exacta del Excel
create or replace function public._real_item(p_pedido bigint, p_producto text, p_color text, p_cantidad int, p_precio numeric, p_ganancia numeric)
returns void language sql set search_path = public as $$
  insert into pedido_items (pedido_id, producto_id, descripcion, color, cantidad, precio_unitario, costo_unitario)
  select p_pedido, id, nombre, p_color, p_cantidad, p_precio, round(p_precio - p_ganancia / p_cantidad, 2)
    from productos where nombre = p_producto;
$$;

-- Ayudante temporal: stock inicial
create or replace function public._real_entrada(p_fecha date, p_producto text, p_color text, p_cantidad int, p_motivo text)
returns void language sql set search_path = public as $$
  insert into movimientos_stock (fecha, producto_id, color, tipo, cantidad, motivo)
  values (p_fecha, (select id from productos where nombre = p_producto), p_color, 'entrada', p_cantidad, p_motivo);
$$;

do $$
declare
  v bigint;
begin
  -- ---------- Configuración ----------
  update configuracion set stock_minimo_defecto = 2 where id = 1;

  -- ---------- Productos (hoja INVENTARIO) ----------
  -- costo = Costo Total (costo base + gasto extra) · precio = Precio Venta
  insert into productos (codigo, nombre, categoria, colores, costo, precio, estado, foto_url, descripcion) values
  ('B001',          'Bolso Kala',                         'Bolsos',     '{}',              27130, 39612.51, 'Activo', null, null),
  ('B002',          'Bolso Cielo',                        'Bolsos',     '{}',              20130, 36284.32, 'Activo', 'assets/productos/bolso-cielo-1.jpg', 'Dos compartimentos con cierre, espacio para zapatillas y bolsillos.'),
  ('B003',          'Bolso Rufina',                       'Bolsos',     '{Violeta}',       23330, 33828.50, 'Activo', 'assets/productos/bolso-rufina-1.jpg', 'Bolso deportivo de nylon, 32 litros, plegable.'),
  ('T001',          'Tote Bag Lienzo',                    'Bolsos',     '{}',               5000,  8210.00, 'Activo', 'assets/productos/tote-bag-cherry.jpg', 'Lienzo natural con estampa.'),
  ('BN000',         'Bandolera Anitta',                   'Carteras',   '{}',              13000, 25797.20, 'Activo', 'assets/productos/bandolera-anita-1.jpg', null),
  ('MB001',         'Mini bag Lucy',                      'Carteras',   '{Rojo}',          16000, 24217.60, 'Activo', 'assets/productos/mini-bag-lucy-1.jpg', null),
  ('CV001 / CV002', 'Cartera Venice',                     'Carteras',   '{Blanco,Negro}',  21000, 28415.10, 'Activo', 'assets/productos/cartera-venice-negro-1.jpg', null),
  ('M001',          'Mochila Zafira',                     'Mochilas',   '{}',              17030, 30149.91, 'Activo', 'assets/productos/mochila-zafira-1.jpg', 'Tela de avión ultra liviana.'),
  ('M002',          'Mochila Ivana',                      'Mochilas',   '{}',              36900, 51903.54, 'Activo', null, null),
  ('M003',          'Mochila Lira',                       'Mochilas',   '{}',              33000, 47830.20, 'Activo', 'assets/productos/mochila-lira-negro-1.jpg', null),
  ('BL001 / BL002', 'Billetera Kaira',                    'Billeteras', '{Negro,Celeste}',  8790, 14433.18, 'Activo', 'assets/productos/billetera-kaira-1.jpg', null),
  ('BL003',         'Billetera Pocket',                   'Billeteras', '{Fucsia}',        12650, 18740.97, 'Activo', 'assets/productos/billetera-pocket-0.jpg', 'Eco cuero con cierre.'),
  ('BL004',         'Billetera Kira',                     'Billeteras', '{}',               8790, 14433.18, 'Activo', 'assets/productos/billetera-kira-1.jpg', 'Nylon resistente y súper liviana.'),
  ('L001',          'Llavero Lua (perrita con cadena)',   'Llaveros',   '{Fucsia}',         3750,  5435.25, 'Activo', 'assets/productos/llavero-lua-1.jpg', null),
  ('L002',          'Llavero Doni',                       'Llaveros',   '{}',               3900,  5652.66, 'Activo', 'assets/productos/llavero-doni-1.jpg', null),
  ('L003',          'Llavero Panchi',                     'Llaveros',   '{}',               3180,  5051.43, 'Activo', null, null),
  ('SC003',         'Scrunchie de Satén',                 'Accesorios', '{Negro}',          1600,  2969.60, 'Activo', null, null),
  ('FS001',         'Funda de Satén',                     'Accesorios', '{Negro}',          4500,  8352.00, 'Activo', 'assets/productos/funda-saten-1.jpg', null),
  ('A001',          'Arito corazón',                      'Accesorios', '{Dorado}',         5400,  7826.76, 'Activo', null, null),
  ('N002',          'Neceser',                            'Accesorios', '{Rosa}',           5400,  8577.90, 'Activo', 'assets/productos/neceser-1.jpg', null),
  ('N003 / N004',   'Neceser Lua',                        'Accesorios', '{Negro,Beige}',   11110, 15554.00, 'Activo', 'assets/productos/neceser-negro-1.jpg', 'Neceser 3 en 1 de poliéster y PVC.'),
  ('MD00',          'Medias elemento',                    'Medias',     '{}',               1940,  3977.00, 'Activo', null, null),
  ('SSPM',          'Scrunchie de Satén x mayor',         'Por mayor',  '{}',               1925,  2790.10, 'Activo', null, 'Venta por mayor, por encargo.'),
  ('FSPM',          'Funda de Satén x mayor',             'Por mayor',  '{}',               4625,  6475.00, 'Activo', null, 'Venta por mayor, por encargo.'),
  (null,            'Cofias simples',                     'Por mayor',  '{}',               4006,  5608.40, 'Activo', null, 'Venta por mayor, por encargo.'),
  ('SSPM',          'Scrunchie de Satén PREMIUM x mayor', 'Por mayor',  '{}',               2775,  4022.09, 'Activo', null, 'Venta por mayor, por encargo.'),
  ('FSPM',          'Funda de Satén PREMIUM x mayor',     'Por mayor',  '{}',               5425,  7595.00, 'Activo', null, 'Venta por mayor, por encargo.'),
  (null,            'Cofias simples PREMIUM',             'Por mayor',  '{}',               4006,  5608.40, 'Activo', null, 'Venta por mayor, por encargo.');

  -- ---------- Stock inicial ----------
  -- Se carga lo que había antes de las ventas (Stock Actual del Excel + lo vendido),
  -- así después de cargar las ventas queda exactamente el "Stock Actual" del Excel.
  perform _real_entrada('2026-03-01', 'Bolso Kala', 'Único', 1, 'Stock inicial (Excel)');
  perform _real_entrada('2026-03-01', 'Bolso Cielo', 'Único', 2, 'Stock inicial (Excel)');
  perform _real_entrada('2026-03-01', 'Bolso Rufina', 'Violeta', 3, 'Stock inicial (Excel)');
  perform _real_entrada('2026-03-01', 'Tote Bag Lienzo', 'Único', 3, 'Stock inicial (Excel)');
  perform _real_entrada('2026-03-01', 'Bandolera Anitta', 'Único', 1, 'Stock inicial (Excel)');
  perform _real_entrada('2026-03-01', 'Mini bag Lucy', 'Rojo', 2, 'Stock inicial (Excel)');
  perform _real_entrada('2026-03-01', 'Cartera Venice', 'Blanco', 2, 'Stock inicial (Excel)');
  perform _real_entrada('2026-03-01', 'Cartera Venice', 'Negro', 5, 'Stock inicial (Excel)');
  perform _real_entrada('2026-03-01', 'Mochila Zafira', 'Único', 1, 'Stock inicial (Excel)');
  perform _real_entrada('2026-03-01', 'Mochila Ivana', 'Único', 1, 'Stock inicial (Excel)');
  perform _real_entrada('2026-03-01', 'Mochila Lira', 'Único', 2, 'Stock inicial (Excel)');
  perform _real_entrada('2026-03-01', 'Billetera Kaira', 'Negro', 2, 'Stock inicial (Excel)');
  perform _real_entrada('2026-03-01', 'Billetera Kaira', 'Celeste', 1, 'Stock inicial (Excel)');
  perform _real_entrada('2026-03-01', 'Billetera Pocket', 'Fucsia', 2, 'Stock inicial (Excel)');
  perform _real_entrada('2026-03-01', 'Billetera Kira', 'Único', 2, 'Stock inicial (Excel)');
  perform _real_entrada('2026-03-01', 'Llavero Lua (perrita con cadena)', 'Fucsia', 2, 'Stock inicial (Excel)');
  perform _real_entrada('2026-03-01', 'Llavero Doni', 'Único', 2, 'Stock inicial (Excel)');
  perform _real_entrada('2026-03-01', 'Llavero Panchi', 'Único', 2, 'Stock inicial (Excel)');
  perform _real_entrada('2026-03-01', 'Funda de Satén', 'Negro', 3, 'Stock inicial (Excel)');
  perform _real_entrada('2026-03-01', 'Arito corazón', 'Dorado', 1, 'Stock inicial (Excel)');
  perform _real_entrada('2026-03-01', 'Neceser', 'Rosa', 1, 'Stock inicial (Excel)');
  perform _real_entrada('2026-03-01', 'Neceser Lua', 'Negro', 2, 'Stock inicial (Excel)');
  perform _real_entrada('2026-03-01', 'Neceser Lua', 'Beige', 2, 'Stock inicial (Excel)');
  perform _real_entrada('2026-03-01', 'Medias elemento', 'Único', 39, 'Stock inicial (Excel)');
  perform _real_entrada('2026-07-29', 'Scrunchie de Satén x mayor', 'Único', 12, 'Compra por mayor (pedido Tía Ana)');
  perform _real_entrada('2026-07-29', 'Funda de Satén x mayor', 'Único', 12, 'Compra por mayor (pedido Tía Ana)');

  -- Los productos por mayor se venden por encargo: mínimo 0 = no avisa "sin stock"
  update stock set minimo = 0 where producto_id in (select id from productos where categoria = 'Por mayor');

  -- ---------- Proveedores (de las hojas INSUMOS y GASTOS) ----------
  insert into proveedores (nombre, que_provee, contacto, notas) values
  ('Papelera sb nacional', 'Moñitos, bolsitas, bolsas de friselina', null, null),
  ('Papelera r3 y Luro',   'Bolsas de papel y de tela, cajitas', null, null),
  ('Terra Bolsas',         'Bolsas Sinan', null, null),
  ('Cecilia',              'Stickers, cierra bolsas, tarjetas con frase', 'Por WhatsApp', null),
  ('Victoria',             'Mini stickers de regalo', 'Por WhatsApp', null),
  ('Luz',                  'Tarjetas para aritos', null, null),
  ('Imprenta Rafaela',     'Stickers Sinan', null, null),
  ('Ween',                 'Stickers para eventos', null, null);

  -- ---------- Insumos y packaging (hoja INSUMOS) ----------
  insert into insumos (codigo, nombre, tipo, stock, costo_unitario, proveedor_id, observaciones)
  select i.codigo, i.nombre, i.tipo, i.stock, i.costo, (select id from proveedores where nombre = i.prov), i.obs
    from (values
      ('INS-MOÑ', 'Moñitos',                          'Regalo',     5,  50::numeric, 'Papelera sb nacional', '2 de los grandes'),
      ('P001',    'Bolsa de papel medianitas',        'Packaging',  2, 400, 'Papelera r3 y Luro', null),
      ('P002',    'Bolsas de tela mediana',           'Packaging',  2, 380, 'Papelera r3 y Luro', null),
      ('P003',    'Bolsas de papel extra grande',     'Packaging',  6, 500, 'Papelera r3 y Luro', null),
      ('P004',    'Cajitas',                          'Packaging',  2, 400, 'Papelera r3 y Luro', null),
      ('P005',    'Bolsas Sinan',                     'Packaging',  8, null, 'Terra Bolsas', null),
      ('P006',    'Bolsas 10x15',                     'Packaging', 85,  15, 'Papelera sb nacional', 'Bolsita para arito'),
      ('P007',    'Bolsas medianas',                  'Packaging', 22,  20, 'Papelera sb nacional', 'Bolsita para scrunchie'),
      ('P008',    'Sticker redondo',                  'Packaging', 19,  50, 'Cecilia', null),
      ('P009',    'Sticker regalo',                   'Packaging',  0, 350, 'Cecilia', null),
      ('P010',    'Mini sticker regalo',              'Packaging',  9,  55, 'Victoria', null),
      ('P011',    'Tarjeta arito',                    'Packaging', 10,  70, 'Luz', null),
      ('P012',    'Sticker Sinan',                    'Packaging',  6,  66, 'Imprenta Rafaela', 'Sticker sn'),
      ('P013',    'Cierra bolsa',                     'Packaging', 20, 130, 'Cecilia', null),
      ('P014',    'Tarjeta frase',                    'Packaging', 15, 220, 'Cecilia', null),
      ('P015',    'Bolsa de friselina medianitas',    'Packaging',  1, 500, 'Papelera sb nacional', 'Comprada el 08/08/2026'),
      ('P016',    'Bolsa de friselina grandes',       'Packaging',  6, 1100, 'Papelera sb nacional', 'Comprada el 08/08/2026'),
      ('P017',    'Bolsa de friselina chiquitas',     'Packaging',  8, 300, 'Papelera sb nacional', 'Comprada el 08/08/2026')
    ) as i(codigo, nombre, tipo, stock, costo, prov, obs);

  -- ---------- Clientas (de la hoja VENTAS) ----------
  insert into clientes (nombre, canal_origen)
  select n, 'Presencial' from unnest(array[
    'Carlos suegro', 'Tía Cole', 'Tía María', 'Ceci', 'Sonia Logística', 'Lorena Logística', 'Yanina Gómez',
    'Abuela Alicia', 'Giovanna', 'Silvana', 'Rocío prima', 'Griselda', 'Camila Kung fu', 'Tía Ana']) as n;

  -- ---------- Evento real ----------
  insert into eventos (nombre, fecha, hora, lugar, descripcion, precio_entrada, cupos, inscriptos, presupuesto, estado)
  values ('Primer encuentro Sinan', '2026-09-19', '10:00', 'Plaza Altos de Laferrere, Gregorio de Laferrere',
          'Un espacio para mujeres que quieran moverse, conocerse y compartir una linda mañana juntas. Ejercicios funcionales al aire libre. Gratuito, cupos limitados.',
          0, 0, 0, 0, 'Realizado');

  -- ---------- Ventas (hoja VENTAS) ----------
  -- Las filas del mismo día y misma clienta quedan en un solo pedido.
  v := _real_pedido('2026-03-12', 'Carlos suegro', 'Transferencia');    perform _real_item(v, 'Bolso Cielo', 'Único', 1, 36284.32, 16154.33);
  v := _real_pedido('2026-03-18', 'Tía Cole', 'Transferencia');         perform _real_item(v, 'Arito corazón', 'Dorado', 1, 7826.76, 2426.76);
  v := _real_pedido('2026-03-20', 'Tía María', 'Transferencia');        perform _real_item(v, 'Medias elemento', 'Único', 1, 3977, 2037);
  v := _real_pedido('2026-03-20', 'Ceci', 'Transferencia');             perform _real_item(v, 'Medias elemento', 'Único', 2, 3977, 2763.17);
  v := _real_pedido('2026-03-23', 'Tía María', 'Efectivo');             perform _real_item(v, 'Medias elemento', 'Único', 2, 3977, 2763.17);
  v := _real_pedido('2026-03-25', 'Sonia Logística', 'Transferencia');  perform _real_item(v, 'Medias elemento', 'Único', 1, 3977, 1381.58);
  v := _real_pedido('2026-03-27', 'Lorena Logística', 'Transferencia'); perform _real_item(v, 'Medias elemento', 'Único', 1, 3977, 1381.58);
  v := _real_pedido('2026-04-05', 'Yanina Gómez', 'Transferencia');     perform _real_item(v, 'Llavero Panchi', 'Único', 1, 5051.43, 1871.43);
  v := _real_pedido('2026-04-07', 'Sonia Logística', 'Transferencia');  perform _real_item(v, 'Llavero Panchi', 'Único', 1, 5051.43, 1871.43);
  v := _real_pedido('2026-04-08', 'Abuela Alicia', 'Efectivo');         perform _real_item(v, 'Billetera Kaira', 'Celeste', 1, 14433.18, 5643.18);
  v := _real_pedido('2026-04-11', 'Giovanna', 'Efectivo');              perform _real_item(v, 'Medias elemento', 'Único', 2, 4071.58, 2763.17);
  v := _real_pedido('2026-05-01', 'Sonia Logística', 'Transferencia');  perform _real_item(v, 'Medias elemento', 'Único', 1, 3977, 1381.58);
  v := _real_pedido('2026-05-03', 'Lorena Logística', 'Efectivo');      perform _real_item(v, 'Medias elemento', 'Único', 1, 3977, 1381.58);
  v := _real_pedido('2026-05-13', 'Sonia Logística', 'Transferencia');  perform _real_item(v, 'Medias elemento', 'Único', 2, 3977, 2763.17);
  v := _real_pedido('2026-05-17', 'Silvana', 'Transferencia');          perform _real_item(v, 'Bolso Kala', 'Único', 1, 39612.51, 12482.51);
  v := _real_pedido('2026-05-19', 'Rocío prima', 'Transferencia');      perform _real_item(v, 'Funda de Satén', 'Negro', 1, 8352, 3852);
  v := _real_pedido('2026-05-28', 'Griselda', 'Transferencia');         perform _real_item(v, 'Billetera Kira', 'Único', 1, 14433.18, 5643.18);
                                                                         perform _real_item(v, 'Medias elemento', 'Único', 2, 3977, 2763.17);
  v := _real_pedido('2026-06-21', 'Tía María', 'Efectivo');             perform _real_item(v, 'Medias elemento', 'Único', 1, 3977, 2037);
  v := _real_pedido('2026-06-22', 'Sonia Logística', 'Efectivo');       perform _real_item(v, 'Medias elemento', 'Único', 2, 3977, 4074);
  v := _real_pedido('2026-07-08', 'Camila Kung fu', 'Transferencia');   perform _real_item(v, 'Bolso Rufina', 'Violeta', 1, 33828.50, 10498.50);
                                                                         perform _real_item(v, 'Medias elemento', 'Único', 1, 3977, 2037);
  v := _real_pedido('2026-07-30', 'Tía Ana', 'Transferencia');          perform _real_item(v, 'Scrunchie de Satén x mayor', 'Único', 12, 2790.10, 10381.14);
                                                                         perform _real_item(v, 'Funda de Satén x mayor', 'Único', 12, 6475, 22200);
  v := _real_pedido('2026-09-10', 'Lorena Logística', 'Transferencia'); perform _real_item(v, 'Medias elemento', 'Único', 1, 3977, 2037);
  v := _real_pedido('2026-09-11', 'Abuela Alicia', 'Transferencia');    perform _real_item(v, 'Medias elemento', 'Único', 1, 3977, 2037);
  v := _real_pedido('2026-09-14', 'Sonia Logística', 'Transferencia');  perform _real_item(v, 'Medias elemento', 'Único', 2, 3977, 4074);
  v := _real_pedido('2026-09-29', 'Sonia Logística', 'Transferencia');  perform _real_item(v, 'Medias elemento', 'Único', 2, 3977, 4074);

  -- Controles: si algo no coincide con el Excel, se cancela todo
  if (select count(*) from pedido_items) <> 28 or (select sum(cantidad) from pedido_items) <> 58 then
    raise exception 'Control: no se cargaron las 28 ventas / 58 unidades del Excel';
  end if;
  if exists (select 1 from pedidos where cliente_id is null) then
    raise exception 'Control: hay ventas sin clienta';
  end if;

  -- La fecha de "última actualización" de cada pedido es la de la venta
  update pedidos set actualizado = fecha + time '12:00';

  -- ---------- Gastos (hoja GASTOS) ----------
  insert into movimientos_financieros (fecha, tipo, categoria, descripcion, monto, medio_pago, proveedor_id, evento_id) values
  ('2026-05-05', 'egreso', 'Regalo aniversario', '4 golosinas (sapito)', 1200, 'Transferencia', null, null),
  ('2026-08-08', 'egreso', 'Papelería', 'Bolsas de friselina de distintas medidas', 9500, 'Transferencia',
     (select id from proveedores where nombre = 'Papelera sb nacional'), null),
  ('2026-09-11', 'egreso', 'Eventos', 'Stickers para el evento', 4800, 'Transferencia',
     (select id from proveedores where nombre = 'Ween'), (select id from eventos where nombre = 'Primer encuentro Sinan'));

  -- ---------- Equipo ----------
  insert into personas (nombre, rol, activa) values ('Pame', 'Dueña', true);
end $$;

-- Borramos los ayudantes temporales
drop function if exists public._real_pedido(date, text, text);
drop function if exists public._real_item(bigint, text, text, int, numeric, numeric);
drop function if exists public._real_entrada(date, text, text, int, text);
