-- =====================================================================
-- SINAN ERP · INSTALACIÓN COMPLETA (todo en un solo archivo)
-- Pegar entero en Supabase > SQL Editor > New query y apretar RUN.
-- Es la unión de 01-tablas, 02-automatismos, 03-seguridad y 04-datos-ejemplo.
-- Se puede volver a correr sin problema: no duplica nada.
-- =====================================================================


-- =====================================================================
-- SINAN ERP · 01 - TABLAS
-- Crea todas las tablas del sistema y sus relaciones.
-- Se puede correr más de una vez: si la tabla ya existe, no la toca.
-- =====================================================================

-- ---------- Configuración (una sola fila con los datos de la marca) ----------
create table if not exists configuracion (
  id                   int primary key default 1 check (id = 1),
  nombre_marca         text not null default 'Sinan',
  frase                text default 'Movete a tu ritmo',
  descripcion          text,
  instagram            text,
  tiktok               text,
  whatsapp             text,
  email                text,
  web                  text,
  razon_social         text,
  cuit                 text,
  condicion_iva        text,
  direccion            text,
  ciudad               text,
  stock_minimo_defecto int not null default 2,
  actualizado          timestamptz not null default now()
);

-- ---------- Productos ----------
create table if not exists productos (
  id          bigint generated by default as identity primary key,
  nombre      text not null,
  categoria   text,
  descripcion text,
  colores     text[] not null default '{}',
  precio      numeric(12,2) not null default 0,
  costo       numeric(12,2) not null default 0,
  estado      text not null default 'Activo'
              check (estado in ('Activo','Pausado','Agotado','Discontinuado')),
  foto_url    text,
  creado      timestamptz not null default now()
);

-- ---------- Stock por producto y color ----------
create table if not exists stock (
  id          bigint generated by default as identity primary key,
  producto_id bigint not null references productos(id) on delete cascade,
  color       text not null default 'Único',
  cantidad    int not null default 0,
  minimo      int,               -- si queda vacío se usa el mínimo de Configuración
  unique (producto_id, color)
);

-- ---------- Clientes ----------
create table if not exists clientes (
  id           bigint generated by default as identity primary key,
  nombre       text not null,
  telefono     text,
  email        text,
  instagram    text,
  canal_origen text,
  ciudad       text,
  notas        text,
  creado       timestamptz not null default now()
);

-- ---------- Eventos ----------
create table if not exists eventos (
  id             bigint generated by default as identity primary key,
  nombre         text not null,
  fecha          date not null,
  hora           text,
  lugar          text,
  descripcion    text,
  precio_entrada numeric(12,2) not null default 0,
  cupos          int not null default 0,
  inscriptos     int not null default 0,
  presupuesto    numeric(12,2) not null default 0,
  estado         text not null default 'Planificando'
                 check (estado in ('Planificando','Confirmado','Realizado','Cancelado')),
  resultado      text,
  creado         timestamptz not null default now()
);

create table if not exists evento_tareas (
  id          bigint generated by default as identity primary key,
  evento_id   bigint not null references eventos(id) on delete cascade,
  tarea       text not null,
  responsable text,
  hecha       boolean not null default false,
  creado      timestamptz not null default now()
);

create table if not exists evento_colaboradores (
  id        bigint generated by default as identity primary key,
  evento_id bigint not null references eventos(id) on delete cascade,
  nombre    text not null,
  rol       text,
  contacto  text,
  aporte    text,
  creado    timestamptz not null default now()
);

-- ---------- Ventas / Pedidos ----------
create table if not exists pedidos (
  id          bigint generated by default as identity primary key,
  fecha       date not null default current_date,
  cliente_id  bigint references clientes(id) on delete set null,
  canal       text not null default 'Instagram'
              check (canal in ('Instagram','Web','WhatsApp','Evento','Otro')),
  estado      text not null default 'Pendiente'
              check (estado in ('Pendiente','Pagado','Preparando','Enviado','Entregado','Cancelado')),
  evento_id   bigint references eventos(id) on delete set null,
  subtotal    numeric(12,2) not null default 0,   -- lo calcula la base sola
  descuento   numeric(12,2) not null default 0,
  envio       numeric(12,2) not null default 0,
  total       numeric(12,2) generated always as (subtotal - descuento + envio) stored,
  notas       text,
  creado      timestamptz not null default now(),
  actualizado timestamptz not null default now()
);

create table if not exists pedido_items (
  id              bigint generated by default as identity primary key,
  pedido_id       bigint not null references pedidos(id) on delete cascade,
  producto_id     bigint references productos(id) on delete set null,
  descripcion     text,            -- nombre del producto al momento de la venta
  color           text not null default 'Único',
  cantidad        int not null check (cantidad > 0),
  precio_unitario numeric(12,2) not null default 0,
  costo_unitario  numeric(12,2) not null default 0
);

-- ---------- Movimientos de stock (entradas, salidas, ajustes) ----------
create table if not exists movimientos_stock (
  id             bigint generated by default as identity primary key,
  fecha          date not null default current_date,
  producto_id    bigint not null references productos(id) on delete cascade,
  color          text not null default 'Único',
  tipo           text not null check (tipo in ('entrada','salida','ajuste')),
  cantidad       int not null,     -- entrada/salida: positivo · ajuste: puede ser negativo
  motivo         text,
  pedido_id      bigint,           -- solo informativo
  pedido_item_id bigint references pedido_items(id) on delete cascade,
  creado         timestamptz not null default now(),
  check (tipo = 'ajuste' or cantidad > 0)
);

-- ---------- Proveedores ----------
create table if not exists proveedores (
  id               bigint generated by default as identity primary key,
  nombre           text not null,
  que_provee       text,
  contacto         text,
  telefono         text,
  email            text,
  instagram        text,
  tiempo_entrega   text,
  condiciones_pago text,
  notas            text,
  creado           timestamptz not null default now()
);

-- ---------- Finanzas (ingresos y egresos que no son ventas) ----------
create table if not exists movimientos_financieros (
  id           bigint generated by default as identity primary key,
  fecha        date not null default current_date,
  tipo         text not null check (tipo in ('ingreso','egreso')),
  categoria    text not null default 'Otros',
  descripcion  text,
  monto        numeric(12,2) not null check (monto >= 0),
  medio_pago   text,
  evento_id    bigint references eventos(id) on delete set null,
  proveedor_id bigint references proveedores(id) on delete set null,
  creado       timestamptz not null default now()
);

-- ---------- Contenido / Marketing ----------
create table if not exists pilares_contenido (
  id          bigint generated by default as identity primary key,
  nombre      text not null,
  descripcion text,
  color       text default '#9cc9e8',
  creado      timestamptz not null default now()
);

create table if not exists publicaciones (
  id          bigint generated by default as identity primary key,
  fecha       date not null,
  red         text not null default 'Instagram',
  formato     text not null default 'Post',
  pilar_id    bigint references pilares_contenido(id) on delete set null,
  titulo      text not null,
  texto       text,
  estado      text not null default 'Idea'
              check (estado in ('Idea','En preparación','Programada','Publicada')),
  link        text,
  alcance     int,
  me_gusta    int,
  comentarios int,
  guardados   int,
  creado      timestamptz not null default now()
);

create table if not exists ideas_contenido (
  id          bigint generated by default as identity primary key,
  titulo      text not null,
  descripcion text,
  pilar_id    bigint references pilares_contenido(id) on delete set null,
  formato     text,
  prioridad   text not null default 'Media' check (prioridad in ('Alta','Media','Baja')),
  usada       boolean not null default false,
  creado      timestamptz not null default now()
);

create table if not exists metricas_instagram (
  id              bigint generated by default as identity primary key,
  fecha           date not null,      -- usamos el día 1 de cada mes
  seguidores      int not null default 0,
  alcance         int,
  interacciones   int,
  visitas_perfil  int,
  clics_link      int,
  notas           text,
  creado          timestamptz not null default now()
);

-- ---------- Equipo ----------
create table if not exists personas (
  id       bigint generated by default as identity primary key,
  nombre   text not null,
  rol      text,
  email    text,
  telefono text,
  activa   boolean not null default true,
  creado   timestamptz not null default now()
);

create table if not exists tareas (
  id           bigint generated by default as identity primary key,
  titulo       text not null,
  descripcion  text,
  persona_id   bigint references personas(id) on delete set null,
  area         text,
  prioridad    text not null default 'Media' check (prioridad in ('Alta','Media','Baja')),
  fecha_limite date,
  estado       text not null default 'Pendiente' check (estado in ('Pendiente','En curso','Hecha')),
  creado       timestamptz not null default now()
);

-- Índices para que las búsquedas sean rápidas
create index if not exists idx_stock_producto      on stock(producto_id);
create index if not exists idx_items_pedido        on pedido_items(pedido_id);
create index if not exists idx_items_producto      on pedido_items(producto_id);
create index if not exists idx_mov_producto        on movimientos_stock(producto_id, color);
create index if not exists idx_mov_item            on movimientos_stock(pedido_item_id);
create index if not exists idx_pedidos_fecha       on pedidos(fecha);
create index if not exists idx_pedidos_cliente     on pedidos(cliente_id);
create index if not exists idx_fin_fecha           on movimientos_financieros(fecha);
create index if not exists idx_publicaciones_fecha on publicaciones(fecha);
create index if not exists idx_tareas_persona      on tareas(persona_id);

-- La fila única de configuración
insert into configuracion (id) values (1) on conflict (id) do nothing;


-- =====================================================================
-- SINAN ERP · 02 - AUTOMATISMOS
-- Cosas que la base hace sola:
--   · Mantener el stock al día con cada entrada / salida / venta
--   · Calcular el total de cada pedido
--   · Devolver el stock si un pedido se cancela o se borra
--   · Crear las filas de stock de cada color al cargar un producto
-- =====================================================================

-- Cuánto suma o resta un movimiento
create or replace function delta_movimiento(p_tipo text, p_cantidad int)
returns int language sql immutable set search_path = public as $$
  select case p_tipo when 'salida' then -p_cantidad else p_cantidad end;
$$;

-- Suma (o resta) unidades al stock de un producto/color
create or replace function aplicar_stock(p_producto bigint, p_color text, p_delta int, p_crear boolean)
returns void language plpgsql set search_path = public as $$
begin
  update stock set cantidad = cantidad + p_delta
   where producto_id = p_producto and color = p_color;
  if not found and p_crear then
    insert into stock (producto_id, color, cantidad) values (p_producto, p_color, p_delta)
    on conflict (producto_id, color) do update set cantidad = stock.cantidad + excluded.cantidad;
  end if;
end $$;

-- Cada movimiento de stock actualiza la tabla stock
create or replace function trg_movimientos_stock()
returns trigger language plpgsql set search_path = public as $$
begin
  if tg_op in ('UPDATE','DELETE') then
    perform aplicar_stock(old.producto_id, old.color, -delta_movimiento(old.tipo, old.cantidad), false);
  end if;
  if tg_op in ('INSERT','UPDATE') then
    perform aplicar_stock(new.producto_id, new.color, delta_movimiento(new.tipo, new.cantidad), true);
    return new;
  end if;
  return old;
end $$;

drop trigger if exists movimientos_stock_sync on movimientos_stock;
create trigger movimientos_stock_sync
  after insert or update of producto_id, color, tipo, cantidad or delete on movimientos_stock
  for each row execute function trg_movimientos_stock();

-- Cada ítem vendido genera su salida de stock y recalcula el total del pedido
create or replace function trg_pedido_items()
returns trigger language plpgsql set search_path = public as $$
declare
  v_pedido_id bigint;
  v_pedido    pedidos%rowtype;
begin
  if tg_op = 'DELETE' then v_pedido_id := old.pedido_id; else v_pedido_id := new.pedido_id; end if;

  if tg_op in ('UPDATE','DELETE') then
    delete from movimientos_stock where pedido_item_id = old.id;
  end if;

  if tg_op in ('INSERT','UPDATE') then
    select * into v_pedido from pedidos where id = new.pedido_id;
    if new.producto_id is not null and v_pedido.estado <> 'Cancelado' then
      insert into movimientos_stock (fecha, producto_id, color, tipo, cantidad, motivo, pedido_id, pedido_item_id)
      values (v_pedido.fecha, new.producto_id, new.color, 'salida', new.cantidad,
              'Venta · pedido #' || new.pedido_id, new.pedido_id, new.id);
    end if;
  end if;

  update pedidos
     set subtotal = (select coalesce(sum(cantidad * precio_unitario), 0) from pedido_items where pedido_id = v_pedido_id)
   where id = v_pedido_id;
  return null;
end $$;

drop trigger if exists pedido_items_sync on pedido_items;
create trigger pedido_items_sync
  after insert or update or delete on pedido_items
  for each row execute function trg_pedido_items();

-- Marca la fecha de última actualización de un pedido
create or replace function trg_pedidos_actualizado()
returns trigger language plpgsql set search_path = public as $$
begin
  -- si se cambia a mano la fecha de actualización se respeta; si no, se pone "ahora"
  if new.actualizado is not distinct from old.actualizado then
    new.actualizado := now();
  end if;
  return new;
end $$;

drop trigger if exists pedidos_actualizado on pedidos;
create trigger pedidos_actualizado
  before update on pedidos
  for each row execute function trg_pedidos_actualizado();

-- Si un pedido se cancela devuelve el stock; si se "des-cancela" lo vuelve a descontar
create or replace function trg_pedidos_estado()
returns trigger language plpgsql set search_path = public as $$
begin
  if new.estado = 'Cancelado' and old.estado <> 'Cancelado' then
    delete from movimientos_stock where pedido_id = new.id and pedido_item_id is not null;
  elsif old.estado = 'Cancelado' and new.estado <> 'Cancelado' then
    insert into movimientos_stock (fecha, producto_id, color, tipo, cantidad, motivo, pedido_id, pedido_item_id)
    select new.fecha, i.producto_id, i.color, 'salida', i.cantidad, 'Venta · pedido #' || new.id, new.id, i.id
      from pedido_items i
     where i.pedido_id = new.id and i.producto_id is not null;
  end if;
  return null;
end $$;

drop trigger if exists pedidos_estado on pedidos;
create trigger pedidos_estado
  after update of estado on pedidos
  for each row execute function trg_pedidos_estado();

-- Al cargar o editar un producto se crea una fila de stock por cada color
create or replace function trg_productos_colores()
returns trigger language plpgsql set search_path = public as $$
begin
  insert into stock (producto_id, color, cantidad)
  select new.id, c, 0
    from unnest(case when coalesce(array_length(new.colores, 1), 0) = 0
                     then array['Único'] else new.colores end) as c
  on conflict (producto_id, color) do nothing;
  return null;
end $$;

drop trigger if exists productos_colores on productos;
create trigger productos_colores
  after insert or update of colores on productos
  for each row execute function trg_productos_colores();

-- Guarda un pedido completo (cabecera + productos) de una sola vez.
-- Si algo falla no se guarda nada a medias.
create or replace function guardar_pedido(p_pedido jsonb, p_items jsonb)
returns bigint language plpgsql set search_path = public as $$
declare
  v_id bigint;
begin
  if p_items is null or jsonb_array_length(p_items) = 0 then
    raise exception 'El pedido tiene que tener al menos un producto';
  end if;

  if coalesce(p_pedido->>'id', '') = '' then
    insert into pedidos (fecha, cliente_id, canal, estado, evento_id, descuento, envio, notas)
    values (
      coalesce((p_pedido->>'fecha')::date, current_date),
      nullif(p_pedido->>'cliente_id', '')::bigint,
      coalesce(p_pedido->>'canal', 'Instagram'),
      coalesce(p_pedido->>'estado', 'Pendiente'),
      nullif(p_pedido->>'evento_id', '')::bigint,
      coalesce(nullif(p_pedido->>'descuento', '')::numeric, 0),
      coalesce(nullif(p_pedido->>'envio', '')::numeric, 0),
      p_pedido->>'notas'
    ) returning id into v_id;
  else
    v_id := (p_pedido->>'id')::bigint;
    delete from pedido_items where pedido_id = v_id;   -- devuelve el stock de los ítems viejos
    update pedidos set
      fecha      = coalesce((p_pedido->>'fecha')::date, fecha),
      cliente_id = nullif(p_pedido->>'cliente_id', '')::bigint,
      canal      = coalesce(p_pedido->>'canal', canal),
      estado     = coalesce(p_pedido->>'estado', estado),
      evento_id  = nullif(p_pedido->>'evento_id', '')::bigint,
      descuento  = coalesce(nullif(p_pedido->>'descuento', '')::numeric, 0),
      envio      = coalesce(nullif(p_pedido->>'envio', '')::numeric, 0),
      notas      = p_pedido->>'notas'
    where id = v_id;
    if not found then raise exception 'No existe el pedido #%', v_id; end if;
  end if;

  insert into pedido_items (pedido_id, producto_id, descripcion, color, cantidad, precio_unitario, costo_unitario)
  select v_id,
         p.id,
         coalesce(p.nombre, i->>'descripcion'),
         coalesce(nullif(i->>'color', ''), 'Único'),
         (i->>'cantidad')::int,
         coalesce(nullif(i->>'precio_unitario', '')::numeric, p.precio, 0),
         coalesce(p.costo, 0)
    from jsonb_array_elements(p_items) as i
    left join productos p on p.id = nullif(i->>'producto_id', '')::bigint;

  return v_id;
end $$;


-- =====================================================================
-- SINAN ERP · 03 - SEGURIDAD
-- · Row Level Security activado en TODAS las tablas
-- · Solo usuarios logueados pueden leer y escribir
-- · Los visitantes anónimos no tienen acceso a nada
-- · Carpeta "fotos" para las imágenes de productos
-- =====================================================================

do $$
declare
  t text;
begin
  foreach t in array array[
    'configuracion','productos','stock','clientes','eventos','evento_tareas',
    'evento_colaboradores','pedidos','pedido_items','movimientos_stock','proveedores',
    'movimientos_financieros','pilares_contenido','publicaciones','ideas_contenido',
    'metricas_instagram','personas','tareas'
  ] loop
    execute format('alter table public.%I enable row level security', t);
    execute format('drop policy if exists "solo usuarios logueados" on public.%I', t);
    execute format('create policy "solo usuarios logueados" on public.%I for all to authenticated using (true) with check (true)', t);
    execute format('revoke all on public.%I from anon', t);
    execute format('grant select, insert, update, delete on public.%I to authenticated', t);
  end loop;
end $$;

grant usage, select on all sequences in schema public to authenticated;
revoke usage, select on all sequences in schema public from anon;

-- Las funciones solo las pueden usar usuarios logueados
revoke execute on function guardar_pedido(jsonb, jsonb)               from public, anon;
revoke execute on function aplicar_stock(bigint, text, int, boolean)  from public, anon;
grant  execute on function guardar_pedido(jsonb, jsonb)               to authenticated;
grant  execute on function aplicar_stock(bigint, text, int, boolean)  to authenticated;

-- ---------- Carpeta de fotos de productos ----------
-- Las fotos se pueden ver con su link (para mostrarlas en pantalla),
-- pero solo un usuario logueado puede subir, cambiar o borrar.
-- (si algo de esta parte falla, el resto igual queda instalado)
do $$
begin
  insert into storage.buckets (id, name, public)
  values ('fotos', 'fotos', true)
  on conflict (id) do nothing;

  drop policy if exists "fotos: ver (logueados)"      on storage.objects;
  drop policy if exists "fotos: subir (logueados)"    on storage.objects;
  drop policy if exists "fotos: cambiar (logueados)"  on storage.objects;
  drop policy if exists "fotos: borrar (logueados)"   on storage.objects;

  create policy "fotos: ver (logueados)"     on storage.objects for select to authenticated using (bucket_id = 'fotos');
  create policy "fotos: subir (logueados)"   on storage.objects for insert to authenticated with check (bucket_id = 'fotos');
  create policy "fotos: cambiar (logueados)" on storage.objects for update to authenticated using (bucket_id = 'fotos');
  create policy "fotos: borrar (logueados)"  on storage.objects for delete to authenticated using (bucket_id = 'fotos');
exception when others then
  raise notice 'No se pudo preparar la carpeta de fotos: %', sqlerrm;
end $$;


-- =====================================================================
-- SINAN ERP · 04 - DATOS DE EJEMPLO
-- Productos reales de Sinan + clientes, ventas, eventos, etc. inventados
-- para poder probar el sistema. Los COSTOS son estimados: cambialos por
-- los reales desde la sección Productos.
-- Solo se cargan si la tabla de productos está vacía (no duplica nada).
-- Para borrarlos: usar 05-borrar-datos-ejemplo.sql
-- =====================================================================

-- Ayudante temporal: arma un pedido a partir de nombres de producto
create or replace function public._seed_pedido(
  p_fecha date, p_cliente text, p_canal text, p_estado text, p_items jsonb,
  p_envio numeric default 0, p_descuento numeric default 0, p_evento text default null)
returns bigint language plpgsql set search_path = public as $$
declare
  v_items jsonb := '[]';
  e jsonb;
begin
  for e in select * from jsonb_array_elements(p_items) loop
    v_items := v_items || jsonb_build_array(jsonb_build_object(
      'producto_id', (select id from productos where nombre = e->>0),
      'color', e->>1,
      'cantidad', (e->>2)::int));
  end loop;
  return guardar_pedido(jsonb_build_object(
    'fecha', p_fecha,
    'cliente_id', (select id from clientes where nombre = p_cliente),
    'canal', p_canal, 'estado', p_estado,
    'envio', p_envio, 'descuento', p_descuento,
    'evento_id', (select id from eventos where nombre = p_evento)), v_items);
end $$;

-- Ayudante temporal: entrada de stock
create or replace function public._seed_entrada(p_fecha date, p_producto text, p_color text, p_cantidad int, p_motivo text)
returns void language sql set search_path = public as $$
  insert into movimientos_stock (fecha, producto_id, color, tipo, cantidad, motivo)
  values (p_fecha, (select id from productos where nombre = p_producto), p_color, 'entrada', p_cantidad, p_motivo);
$$;

do $$
begin
  if exists (select 1 from productos) then
    raise notice 'Ya hay productos cargados: no se cargan los datos de ejemplo.';
    return;
  end if;

  -- ---------- Configuración ----------
  update configuracion set
    nombre_marca = 'Sinan',
    frase = 'Movete a tu ritmo',
    descripcion = 'Accesorios que se adaptan a tu ritmo, especiales para mujeres que buscan comodidad y bienestar.',
    instagram = '@sinan.bags',
    whatsapp = '+54 9 11 2672-4433',
    web = 'https://sinan.mitiendanube.com',
    ciudad = 'Buenos Aires, Argentina',
    stock_minimo_defecto = 2
  where id = 1;

  -- ---------- Productos (los reales de la web) ----------
  insert into productos (nombre, categoria, descripcion, colores, precio, costo, estado, foto_url) values
  ('Billetera Kaira',      'Billeteras', 'Material sintético resistente, diseño moderno en relieve. Compacta y práctica.', '{Negro,Celeste}', 14500, 6800,  'Activo', 'assets/productos/billetera-kaira-1.jpg'),
  ('Billetera Kira',       'Billeteras', 'Nylon resistente y súper liviana. Chiquita y cómoda para el día a día.',       '{}',              14500, 6500,  'Activo', 'assets/productos/billetera-kira-1.jpg'),
  ('Billetera Pocket',     'Billeteras', 'Eco cuero con cierre. Seis compartimientos para tarjetas y dos para billetes.', '{}',              18900, 8900,  'Activo', 'assets/productos/billetera-pocket-0.jpg'),
  ('Bolso Cielo',          'Bolsos',     'Dos compartimentos con cierre, espacio para zapatillas y bolsillos.',           '{}',              36700, 17500, 'Activo', 'assets/productos/bolso-cielo-1.jpg'),
  ('Tote Bag Cherry',      'Bolsos',     'Lienzo natural con estampa "You are a cherry on top".',                         '{}',              8300,  3600,  'Activo', 'assets/productos/tote-bag-cherry.jpg'),
  ('Bolso Rufina',         'Bolsos',     'Bolso deportivo de nylon, 32 litros, plegable. Violeta liso.',                  '{Violeta}',       37500, 18000, 'Activo', 'assets/productos/bolso-rufina-1.jpg'),
  ('Mochila Zafira',       'Mochilas',   'Tela de avión ultra liviana. Bolsillo interno, externo y laterales.',           '{}',              30000, 14000, 'Activo', 'assets/productos/mochila-zafira-1.jpg'),
  ('Mochila Lira',         'Mochilas',   'Compartimiento con separador, bolsillo frontal y dos laterales. Forrada.',      '{Beige,Negro}',   47900, 23000, 'Activo', 'assets/productos/mochila-lira-negro-1.jpg'),
  ('Bandolera Anita',      'Carteras',   'Bandolera cómoda para llevar lo esencial.',                                     '{}',              25900, 12000, 'Activo', 'assets/productos/bandolera-anita-1.jpg'),
  ('Cartera Venice',       'Carteras',   'Cartera para salidas y momentos especiales. En oferta.',                        '{Blanco,Negro}',  28000, 13500, 'Activo', 'assets/productos/cartera-venice-negro-1.jpg'),
  ('Mini bag Lucy',        'Carteras',   'Mini bag práctica y liviana. En oferta.',                                       '{}',              24000, 11500, 'Activo', 'assets/productos/mini-bag-lucy-1.jpg'),
  ('Llavero Doni',         'Llaveros',   'Detalles que hacen la diferencia.',                                             '{}',              5600,  2200,  'Activo', 'assets/productos/llavero-doni-1.jpg'),
  ('Llavero Lua',          'Llaveros',   'Detalles que hacen la diferencia.',                                             '{}',              5600,  2200,  'Activo', 'assets/productos/llavero-lua-1.jpg'),
  ('Neceser',              'Accesorios', 'Neceser práctico para el día a día.',                                           '{}',              8500,  3800,  'Activo', 'assets/productos/neceser-1.jpg'),
  ('Neceser Lua',          'Accesorios', 'Neceser 3 en 1 de poliéster y PVC súper resistente. Ideal para regalar.',       '{Rosa,Celeste,Negro}', 15500, 7000, 'Activo', 'assets/productos/neceser-celeste-1.jpg'),
  ('Funda de satén',       'Accesorios', 'Funda de almohada de satén, cuida tu pelo mientras dormís.',                    '{}',              8000,  3200,  'Activo', 'assets/productos/funda-saten-1.jpg'),
  ('Medias Offline',       'Medias',     'Medias suaves con diseño Offline.',                                             '{}',              4000,  1500,  'Activo', 'assets/productos/medias-offline-1.jpg'),
  ('Medias Osito Corazón', 'Medias',     'Medias suaves con osito y corazón.',                                            '{}',              4000,  1500,  'Activo', 'assets/productos/medias-osito-corazon-1.jpg'),
  ('Medias Soff',          'Medias',     'Suaves, hipoalergénicas y con puntera reforzada. Varios colores con rayitas.',  '{}',              4000,  1500,  'Activo', 'assets/productos/medias-soff-1.png');

  -- ---------- Stock inicial (compras) ----------
  perform _seed_entrada('2026-05-02', 'Billetera Kaira', 'Negro', 3, 'Compra inicial');
  perform _seed_entrada('2026-05-02', 'Billetera Kaira', 'Celeste', 2, 'Compra inicial');
  perform _seed_entrada('2026-05-02', 'Billetera Kira', 'Único', 3, 'Compra inicial');
  perform _seed_entrada('2026-05-02', 'Billetera Pocket', 'Único', 3, 'Compra inicial');
  perform _seed_entrada('2026-05-02', 'Bolso Cielo', 'Único', 3, 'Compra inicial');
  perform _seed_entrada('2026-05-02', 'Tote Bag Cherry', 'Único', 6, 'Compra inicial');
  perform _seed_entrada('2026-05-02', 'Bolso Rufina', 'Violeta', 4, 'Compra inicial');
  perform _seed_entrada('2026-05-02', 'Mochila Zafira', 'Único', 3, 'Compra inicial');
  perform _seed_entrada('2026-05-02', 'Mochila Lira', 'Beige', 2, 'Compra inicial');
  perform _seed_entrada('2026-05-02', 'Mochila Lira', 'Negro', 3, 'Compra inicial');
  perform _seed_entrada('2026-05-02', 'Bandolera Anita', 'Único', 2, 'Compra inicial');
  perform _seed_entrada('2026-05-02', 'Cartera Venice', 'Blanco', 2, 'Compra inicial');
  perform _seed_entrada('2026-05-02', 'Cartera Venice', 'Negro', 2, 'Compra inicial');
  perform _seed_entrada('2026-05-02', 'Mini bag Lucy', 'Único', 4, 'Compra inicial');
  perform _seed_entrada('2026-05-02', 'Llavero Doni', 'Único', 4, 'Compra inicial');
  perform _seed_entrada('2026-05-02', 'Llavero Lua', 'Único', 4, 'Compra inicial');
  perform _seed_entrada('2026-05-02', 'Neceser', 'Único', 2, 'Compra inicial');
  perform _seed_entrada('2026-05-02', 'Neceser Lua', 'Rosa', 2, 'Compra inicial');
  perform _seed_entrada('2026-05-02', 'Neceser Lua', 'Celeste', 2, 'Compra inicial');
  perform _seed_entrada('2026-05-02', 'Neceser Lua', 'Negro', 3, 'Compra inicial');
  perform _seed_entrada('2026-05-02', 'Funda de satén', 'Único', 3, 'Compra inicial');
  perform _seed_entrada('2026-05-02', 'Medias Offline', 'Único', 1, 'Compra inicial');
  perform _seed_entrada('2026-05-02', 'Medias Osito Corazón', 'Único', 3, 'Compra inicial');
  perform _seed_entrada('2026-05-02', 'Medias Soff', 'Único', 10, 'Compra inicial');
  perform _seed_entrada('2026-08-01', 'Medias Soff', 'Único', 6, 'Reposición');

  -- Los productos caros se venden de a uno: mínimo 1 en vez del general (2)
  update stock set minimo = 1
   where producto_id in (select id from productos
                          where nombre in ('Bolso Cielo','Mochila Lira','Mochila Zafira','Bandolera Anita','Cartera Venice','Bolso Rufina'));

  -- ---------- Clientes (inventados) ----------
  insert into clientes (nombre, telefono, email, instagram, canal_origen, ciudad, notas) values
  ('Lucía Fernández',  '11 5321-4410', 'lucia.fernandez@mail.com', '@lufernandez', 'Instagram', 'CABA',          'Le encantan los bolsos grandes.'),
  ('Valentina Gómez',  '11 6012-3398', 'valegomez@mail.com',       '@vale.gomez',  'Instagram', 'Vicente López', null),
  ('Carla Ruiz',       '11 4788-2201', 'carla.ruiz@mail.com',      null,           'Web',       'La Plata',      'Prefiere envío por Andreani.'),
  ('Florencia Díaz',   '11 3345-9087', 'flor.diaz@mail.com',       '@flordiaz',    'Instagram', 'CABA',          null),
  ('Martina López',    '11 2290-7765', null,                       '@martulopez',  'WhatsApp',  'Quilmes',       null),
  ('Sofía Martínez',   '11 6677-1123', 'sofi.martinez@mail.com',   '@sofimartinez','Web',       'Rosario',       'Clienta frecuente.'),
  ('Camila Pereyra',   '11 5098-6634', null,                       '@cami.pereyra','Evento',    'CABA',          'La conocimos en el primer encuentro.'),
  ('Julieta Romero',   '11 4402-8890', 'juli.romero@mail.com',     '@juliromero',  'Instagram', 'San Isidro',    null),
  ('Agustina Sosa',    '11 3876-5512', 'agus.sosa@mail.com',       null,           'Web',       'Córdoba',       null),
  ('Paula Herrera',    '11 2765-4309', null,                       '@pauherrera',  'Otro',      'CABA',          'Vino recomendada por Lucía.'),
  ('Micaela Torres',   '11 6543-2198', 'mica.torres@mail.com',     '@micatorres',  'Instagram', 'Tigre',         null),
  ('Rocío Álvarez',    '11 4123-7765', null,                       '@rochi.alvarez','Instagram','Lanús',         null);

  -- ---------- Proveedores (inventados) ----------
  insert into proveedores (nombre, que_provee, contacto, telefono, email, instagram, tiempo_entrega, condiciones_pago, notas) values
  ('Marroquinería del Once',   'Bolsos, mochilas y carteras',          'Rubén',   '11 4961-2200', 'ventas@marroquineriaonce.com', null,              '7 a 10 días',  '50% seña, 50% al retirar', 'Pedido mínimo 10 unidades.'),
  ('Accesorios del Sur',       'Billeteras, neceseres y llaveros',     'Analía',  '11 4302-7781', 'pedidos@accesoriosdelsur.com',  '@accesoriosdelsur','5 días',       'Transferencia contra entrega', null),
  ('Medias Lindas Mayorista',  'Medias',                               'Graciela','11 4867-3390', null,                            '@medias.lindas',  '3 días',       'Efectivo o transferencia', 'Hace descuento por docena.'),
  ('Packaging Express',        'Bolsas, cajas, papel de seda, etiquetas','Diego',  '11 5566-1209', 'hola@packagingexpress.com',     '@packaging.express','10 días',     'Pago anticipado', null),
  ('Gráfica Norte',            'Tarjetas, stickers y flyers',          'Sole',    '11 3021-4456', 'graficanorte@mail.com',         null,              '4 días hábiles','50% seña', null);

  -- ---------- Eventos ----------
  insert into eventos (nombre, fecha, hora, lugar, descripcion, precio_entrada, cupos, inscriptos, presupuesto, estado, resultado) values
  ('Primer encuentro Sinan', '2026-09-19', '17:00', 'Café Botánico, Palermo', 'Encuentro con clientas: merienda, charla sobre bienestar y sorteo.', 8000, 20, 18, 120000, 'Realizado',
   'Muy buena convocatoria (18 de 20). Se vendieron medias y accesorios. Repetir en primavera con más cupos.'),
  ('Desayuno Día de la Madre', '2026-10-17', '10:00', 'Espacio Verde, Belgrano', 'Desayuno para venir con mamá, con regalos y descuentos especiales.', 12000, 25, 14, 150000, 'Confirmado', null),
  ('Feria de Primavera', '2026-11-14', '11:00', 'Mercado de Diseño, San Telmo', 'Puesto en feria de diseño independiente.', 0, 0, 0, 80000, 'Planificando', null);

  insert into evento_tareas (evento_id, tarea, responsable, hecha)
  select e.id, t.tarea, t.resp, t.hecha
    from eventos e
    join (values
      ('Primer encuentro Sinan', 'Reservar el lugar', 'Pame', true),
      ('Primer encuentro Sinan', 'Publicar flyer en Instagram', 'Lola', true),
      ('Primer encuentro Sinan', 'Comprar regalos para el sorteo', 'Pame', true),
      ('Primer encuentro Sinan', 'Armar mesa de productos', 'Pame', true),
      ('Desayuno Día de la Madre', 'Señar el espacio', 'Pame', true),
      ('Desayuno Día de la Madre', 'Confirmar menú con la pastelería', 'Pame', true),
      ('Desayuno Día de la Madre', 'Publicar invitación y abrir inscripción', 'Lola', true),
      ('Desayuno Día de la Madre', 'Armar bolsitas de regalo', 'Pame', false),
      ('Desayuno Día de la Madre', 'Coordinar fotos del evento', 'Mica', false),
      ('Desayuno Día de la Madre', 'Llevar posnet / QR de pago', 'Pame', false),
      ('Feria de Primavera', 'Inscribirse en la feria', 'Pame', false),
      ('Feria de Primavera', 'Conseguir mesa y mantel', 'Pame', false)
    ) as t(evento, tarea, resp, hecha) on t.evento = e.nombre;

  insert into evento_colaboradores (evento_id, nombre, rol, contacto, aporte)
  select e.id, c.nombre, c.rol, c.contacto, c.aporte
    from eventos e
    join (values
      ('Primer encuentro Sinan', 'Café Botánico', 'Lugar', '@cafebotanico', 'Espacio y merienda'),
      ('Primer encuentro Sinan', 'Mica', 'Fotografía', '11 5555-0101', 'Fotos del evento'),
      ('Desayuno Día de la Madre', 'Dulce Abril', 'Pastelería', '@dulceabril', 'Desayuno para 25 personas'),
      ('Desayuno Día de la Madre', 'Mica', 'Fotografía', '11 5555-0101', 'Fotos del evento')
    ) as c(evento, nombre, rol, contacto, aporte) on c.evento = e.nombre;

  -- ---------- Ventas (al guardarlas se descuenta el stock solo) ----------
  perform _seed_pedido('2026-05-06', 'Lucía Fernández', 'Instagram', 'Entregado', '[["Bolso Cielo","Único",1]]');
  perform _seed_pedido('2026-05-12', 'Valentina Gómez', 'WhatsApp',  'Entregado', '[["Medias Soff","Único",2],["Medias Offline","Único",1]]');
  perform _seed_pedido('2026-05-20', 'Carla Ruiz',      'Web',       'Entregado', '[["Mochila Zafira","Único",1]]', 4500);
  perform _seed_pedido('2026-05-28', 'Florencia Díaz',  'Instagram', 'Entregado', '[["Billetera Kaira","Negro",1],["Llavero Lua","Único",1]]');
  perform _seed_pedido('2026-06-03', 'Martina López',   'Instagram', 'Entregado', '[["Mochila Lira","Negro",1]]');
  perform _seed_pedido('2026-06-10', 'Sofía Martínez',  'Web',       'Entregado', '[["Cartera Venice","Negro",1]]', 4500);
  perform _seed_pedido('2026-06-18', 'Lucía Fernández', 'WhatsApp',  'Entregado', '[["Neceser Lua","Rosa",1],["Funda de satén","Único",1]]');
  perform _seed_pedido('2026-06-25', 'Camila Pereyra',  'Instagram', 'Entregado', '[["Bandolera Anita","Único",1]]');
  perform _seed_pedido('2026-07-02', 'Julieta Romero',  'Instagram', 'Entregado', '[["Bolso Rufina","Violeta",1]]');
  perform _seed_pedido('2026-07-09', 'Agustina Sosa',   'Web',       'Entregado', '[["Billetera Pocket","Único",1],["Medias Osito Corazón","Único",1]]', 4500);
  perform _seed_pedido('2026-07-15', 'Valentina Gómez', 'Instagram', 'Entregado', '[["Mini bag Lucy","Único",1]]');
  perform _seed_pedido('2026-07-22', 'Paula Herrera',   'Otro',      'Entregado', '[["Tote Bag Cherry","Único",2]]');
  perform _seed_pedido('2026-07-30', 'Carla Ruiz',      'WhatsApp',  'Entregado', '[["Billetera Kira","Único",1],["Llavero Doni","Único",1]]');
  perform _seed_pedido('2026-08-05', 'Micaela Torres',  'Instagram', 'Entregado', '[["Mochila Lira","Beige",1]]');
  perform _seed_pedido('2026-08-12', 'Sofía Martínez',  'Instagram', 'Entregado', '[["Neceser Lua","Celeste",1],["Medias Soff","Único",2]]', 0, 1500);
  perform _seed_pedido('2026-08-19', 'Florencia Díaz',  'Web',       'Entregado', '[["Bolso Cielo","Único",1]]', 4500);
  perform _seed_pedido('2026-08-27', 'Rocío Álvarez',   'Instagram', 'Cancelado', '[["Mochila Zafira","Único",1]]');
  perform _seed_pedido('2026-09-02', 'Martina López',   'WhatsApp',  'Entregado', '[["Cartera Venice","Blanco",1]]');
  perform _seed_pedido('2026-09-08', 'Julieta Romero',  'Instagram', 'Entregado', '[["Neceser","Único",1],["Billetera Kaira","Celeste",1]]');
  perform _seed_pedido('2026-09-19', 'Agustina Sosa',   'Evento',    'Entregado', '[["Medias Soff","Único",3]]', 0, 0, 'Primer encuentro Sinan');
  perform _seed_pedido('2026-09-19', 'Paula Herrera',   'Evento',    'Entregado', '[["Llavero Lua","Único",1],["Llavero Doni","Único",1]]', 0, 0, 'Primer encuentro Sinan');
  perform _seed_pedido('2026-09-19', 'Camila Pereyra',  'Evento',    'Entregado', '[["Funda de satén","Único",1],["Neceser Lua","Negro",1]]', 0, 0, 'Primer encuentro Sinan');
  perform _seed_pedido('2026-09-24', 'Lucía Fernández', 'Instagram', 'Entregado', '[["Bolso Rufina","Violeta",1]]');
  perform _seed_pedido('2026-09-29', 'Micaela Torres',  'Web',       'Enviado',   '[["Mochila Zafira","Único",1]]', 4500);
  perform _seed_pedido('2026-10-01', 'Valentina Gómez', 'Instagram', 'Pagado',    '[["Billetera Kaira","Negro",1],["Medias Soff","Único",1]]');
  perform _seed_pedido('2026-10-03', 'Rocío Álvarez',   'WhatsApp',  'Preparando','[["Mini bag Lucy","Único",1]]');
  perform _seed_pedido('2026-10-04', 'Sofía Martínez',  'Instagram', 'Pendiente', '[["Mochila Lira","Negro",1]]');
  perform _seed_pedido('2026-10-05', 'Carla Ruiz',      'Web',       'Pendiente', '[["Tote Bag Cherry","Único",1],["Medias Osito Corazón","Único",1]]', 4500);

  -- Fechas de carga y última actualización realistas (para las alertas)
  update pedidos set creado = fecha::timestamptz + interval '12 hours',
                     actualizado = case when estado in ('Entregado','Cancelado') then fecha + 4 else fecha + 1 end;

  -- ---------- Finanzas (gastos y otros ingresos) ----------
  insert into movimientos_financieros (fecha, tipo, categoria, descripcion, monto, medio_pago, evento_id, proveedor_id) values
  ('2026-05-02', 'egreso', 'Mercadería',  'Compra inicial bolsos, mochilas y carteras', 280000, 'Transferencia', null, (select id from proveedores where nombre = 'Marroquinería del Once')),
  ('2026-05-02', 'egreso', 'Mercadería',  'Compra inicial billeteras, neceseres y llaveros', 120000, 'Transferencia', null, (select id from proveedores where nombre = 'Accesorios del Sur')),
  ('2026-05-02', 'egreso', 'Mercadería',  'Compra inicial medias', 22500, 'Efectivo', null, (select id from proveedores where nombre = 'Medias Lindas Mayorista')),
  ('2026-05-08', 'egreso', 'Packaging',   'Bolsas, papel de seda y etiquetas', 25000, 'Transferencia', null, (select id from proveedores where nombre = 'Packaging Express')),
  ('2026-05-15', 'egreso', 'Diseño e imprenta', 'Tarjetas de agradecimiento y stickers', 12000, 'Transferencia', null, (select id from proveedores where nombre = 'Gráfica Norte')),
  ('2026-05-31', 'egreso', 'Comisiones',  'Comisiones Mercado Pago mayo', 3900, 'Mercado Pago', null, null),
  ('2026-06-05', 'egreso', 'Publicidad',  'Promoción en Instagram', 15000, 'Tarjeta', null, null),
  ('2026-06-10', 'egreso', 'Servicios',   'Canva Pro', 7000, 'Tarjeta', null, null),
  ('2026-06-30', 'egreso', 'Comisiones',  'Comisiones Mercado Pago junio', 5100, 'Mercado Pago', null, null),
  ('2026-07-05', 'egreso', 'Publicidad',  'Promoción en Instagram', 15000, 'Tarjeta', null, null),
  ('2026-07-10', 'egreso', 'Servicios',   'Canva Pro', 7000, 'Tarjeta', null, null),
  ('2026-07-20', 'egreso', 'Envíos',      'Envíos Andreani julio', 9800, 'Transferencia', null, null),
  ('2026-07-31', 'egreso', 'Comisiones',  'Comisiones Mercado Pago julio', 4300, 'Mercado Pago', null, null),
  ('2026-08-01', 'egreso', 'Mercadería',  'Reposición medias Soff', 9000, 'Efectivo', null, (select id from proveedores where nombre = 'Medias Lindas Mayorista')),
  ('2026-08-05', 'egreso', 'Publicidad',  'Promoción en Instagram', 15000, 'Tarjeta', null, null),
  ('2026-08-10', 'egreso', 'Servicios',   'Canva Pro', 7000, 'Tarjeta', null, null),
  ('2026-08-14', 'egreso', 'Packaging',   'Cajas para regalo', 18000, 'Transferencia', null, (select id from proveedores where nombre = 'Packaging Express')),
  ('2026-08-31', 'egreso', 'Comisiones',  'Comisiones Mercado Pago agosto', 3600, 'Mercado Pago', null, null),
  ('2026-09-05', 'egreso', 'Publicidad',  'Promoción del primer encuentro', 20000, 'Tarjeta', (select id from eventos where nombre = 'Primer encuentro Sinan'), null),
  ('2026-09-10', 'egreso', 'Servicios',   'Canva Pro', 7000, 'Tarjeta', null, null),
  ('2026-09-17', 'egreso', 'Eventos',     'Merienda y espacio - Café Botánico', 60000, 'Transferencia', (select id from eventos where nombre = 'Primer encuentro Sinan'), null),
  ('2026-09-18', 'egreso', 'Eventos',     'Decoración y regalos para el sorteo', 28000, 'Efectivo', (select id from eventos where nombre = 'Primer encuentro Sinan'), null),
  ('2026-09-19', 'ingreso','Entradas de eventos', 'Entradas primer encuentro (18 × $ 8.000)', 144000, 'Mercado Pago', (select id from eventos where nombre = 'Primer encuentro Sinan'), null),
  ('2026-09-30', 'egreso', 'Comisiones',  'Comisiones Mercado Pago septiembre', 6200, 'Mercado Pago', null, null),
  ('2026-10-02', 'egreso', 'Eventos',     'Seña espacio desayuno Día de la Madre', 30000, 'Transferencia', (select id from eventos where nombre = 'Desayuno Día de la Madre'), null),
  ('2026-10-03', 'ingreso','Entradas de eventos', 'Entradas vendidas desayuno (14 × $ 12.000)', 168000, 'Mercado Pago', (select id from eventos where nombre = 'Desayuno Día de la Madre'), null),
  ('2026-10-05', 'egreso', 'Publicidad',  'Promoción Día de la Madre', 18000, 'Tarjeta', null, null);

  -- ---------- Contenido ----------
  insert into pilares_contenido (nombre, descripcion, color) values
  ('Producto',               'Mostrar los productos, sus detalles y cómo se usan.', '#477ab3'),
  ('Bienestar y movimiento', 'Moverse a tu ritmo: rutinas, comodidad, autocuidado.', '#9cc9e8'),
  ('Detrás de escena',       'Cómo se elige, se arma y se empaca cada pedido.', '#12364e'),
  ('Comunidad',              'Reseñas, fotos de clientas y eventos.', '#c9a27e');

  insert into publicaciones (fecha, red, formato, pilar_id, titulo, texto, estado, link, alcance, me_gusta, comentarios, guardados)
  select p.fecha::date, p.red, p.formato, (select id from pilares_contenido where nombre = p.pilar), p.titulo, p.texto, p.estado, null, p.alcance, p.mg, p.com, p.gu
    from (values
      ('2026-09-03', 'Instagram', 'Carrusel', 'Producto',               'Todo lo que entra en la Mochila Lira', 'Te mostramos todo lo que podés llevar 🎒', 'Publicada', 2350, 186, 14, 41),
      ('2026-09-08', 'Instagram', 'Reel',     'Bienestar y movimiento', 'Mañana a mi ritmo', 'Una mañana tranqui con el Bolso Cielo.', 'Publicada', 5120, 402, 23, 88),
      ('2026-09-12', 'Instagram', 'Historia', 'Comunidad',              'Cuenta regresiva primer encuentro', null, 'Publicada', 980, null, null, null),
      ('2026-09-16', 'Instagram', 'Post',     'Detrás de escena',       'Así preparamos cada pedido', 'Papel de seda, tarjetita y mucho amor.', 'Publicada', 1890, 154, 9, 12),
      ('2026-09-21', 'Instagram', 'Carrusel', 'Comunidad',              'Fotos del primer encuentro', '¡Gracias a todas las que vinieron! 💙', 'Publicada', 3410, 298, 31, 25),
      ('2026-09-27', 'Instagram', 'Reel',     'Producto',               'Medias Soff: elegí tu color', null, 'Publicada', 2780, 210, 18, 30),
      ('2026-10-01', 'Instagram', 'Post',     'Comunidad',              'Invitación desayuno Día de la Madre', 'Reservá tu lugar para venir con mamá.', 'Publicada', 2100, 175, 20, 16),
      ('2026-10-07', 'Instagram', 'Carrusel', 'Producto',               'Guía de regalos Día de la Madre', 'Ideas para cada mamá.', 'Programada', null, null, null, null),
      ('2026-10-10', 'Instagram', 'Reel',     'Bienestar y movimiento', 'Rutina de domingo con la Mochila Zafira', null, 'En preparación', null, null, null, null),
      ('2026-10-14', 'Instagram', 'Historia', 'Detrás de escena',       'Armando las bolsitas del desayuno', null, 'Idea', null, null, null, null),
      ('2026-10-18', 'Instagram', 'Post',     'Comunidad',              'Feliz día a todas las mamás', null, 'Programada', null, null, null, null),
      ('2026-10-24', 'TikTok',    'Reel',     'Producto',               'Qué hay en mi Bolso Rufina', null, 'Idea', null, null, null, null)
    ) as p(fecha, red, formato, pilar, titulo, texto, estado, alcance, mg, com, gu);

  insert into ideas_contenido (titulo, descripcion, pilar_id, formato, prioridad, usada)
  select i.titulo, i.descr, (select id from pilares_contenido where nombre = i.pilar), i.formato, i.prio, i.usada
    from (values
      ('Antes y después de organizar la cartera', 'Mostrar cómo cambia todo con el Neceser Lua.', 'Producto', 'Reel', 'Alta', false),
      ('Clientas contando para qué usan su Sinan', 'Pedir videos cortitos a clientas.', 'Comunidad', 'Reel', 'Alta', false),
      ('5 tips para cuidar tu espalda con la mochila', null, 'Bienestar y movimiento', 'Carrusel', 'Media', false),
      ('Cómo elijo los productos', 'Contar la historia de la marca.', 'Detrás de escena', 'Post', 'Media', false),
      ('Sorteo con marca amiga', 'Buscar una marca de bienestar para sortear juntas.', 'Comunidad', 'Post', 'Baja', false),
      ('Unboxing de un pedido', null, 'Detrás de escena', 'Reel', 'Media', true)
    ) as i(titulo, descr, pilar, formato, prio, usada);

  insert into metricas_instagram (fecha, seguidores, alcance, interacciones, visitas_perfil, clics_link, notas) values
  ('2026-05-01',  820,  9800,  610,  740,  52, null),
  ('2026-06-01',  905, 12400,  780,  910,  71, 'Empezamos a pautar.'),
  ('2026-07-01',  980, 13900,  845, 1020,  80, null),
  ('2026-08-01', 1060, 15100,  910, 1150,  94, null),
  ('2026-09-01', 1185, 19800, 1320, 1610, 132, 'Pico por el primer encuentro.');

  -- ---------- Equipo ----------
  insert into personas (nombre, rol, email, telefono, activa) values
  ('Pame', 'Dueña · ventas, compras y eventos', null, null, true),
  ('Lola', 'Community manager (freelance)', 'lola.cm@mail.com', '11 5555-0202', true),
  ('Mica', 'Fotografía (freelance)', 'mica.foto@mail.com', '11 5555-0101', true);

  insert into tareas (titulo, descripcion, persona_id, area, prioridad, fecha_limite, estado)
  select t.titulo, t.descr, (select id from personas where nombre = t.persona), t.area, t.prio, t.fecha::date, t.estado
    from (values
      ('Pedir reposición de Billetera Kaira', 'Quedan pocas unidades de los dos colores.', 'Pame', 'Compras', 'Alta', '2026-10-08', 'Pendiente'),
      ('Despachar pedido de Rocío', 'Mini bag Lucy por WhatsApp.', 'Pame', 'Ventas', 'Alta', '2026-10-06', 'En curso'),
      ('Armar guía de regalos Día de la Madre', null, 'Lola', 'Contenido', 'Alta', '2026-10-06', 'En curso'),
      ('Sesión de fotos productos nuevos', 'Neceser Lua y Bolso Rufina.', 'Mica', 'Contenido', 'Media', '2026-10-12', 'Pendiente'),
      ('Cargar costos reales de todos los productos', null, 'Pame', 'Administración', 'Media', '2026-10-15', 'Pendiente'),
      ('Inscribirse en la Feria de Primavera', null, 'Pame', 'Eventos', 'Media', '2026-10-20', 'Pendiente'),
      ('Responder reseñas de septiembre', null, 'Lola', 'Contenido', 'Baja', '2026-09-30', 'Hecha')
    ) as t(titulo, descr, persona, area, prio, fecha, estado);
end $$;

-- Borramos los ayudantes temporales
drop function if exists public._seed_pedido(date, text, text, text, jsonb, numeric, numeric, text);
drop function if exists public._seed_entrada(date, text, text, int, text);
